// TODO figure out a way to keep this mock code
// out of the produciton release to avoid code bloat
// e.g. if (!kReleaseMode) {

const mockNrl2022Full = [
  {
    "MatchNumber": 1,
    "RoundNumber": 1,
    "DateUtc": "2022-03-10 09:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 2,
    "RoundNumber": 1,
    "DateUtc": "2022-03-11 07:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 19
  },
  {
    "MatchNumber": 3,
    "RoundNumber": 1,
    "DateUtc": "2022-03-11 09:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 11,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 4,
    "RoundNumber": 1,
    "DateUtc": "2022-03-12 04:00:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 5,
    "RoundNumber": 1,
    "DateUtc": "2022-03-12 06:30:00Z",
    "Location": "Sunshine Coast Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 6,
    "RoundNumber": 1,
    "DateUtc": "2022-03-12 08:35:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 7,
    "RoundNumber": 1,
    "DateUtc": "2022-03-13 05:05:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 8,
    "RoundNumber": 1,
    "DateUtc": "2022-03-13 07:15:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 4,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 9,
    "RoundNumber": 2,
    "DateUtc": "2022-03-17 09:05:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 15,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 10,
    "RoundNumber": 2,
    "DateUtc": "2022-03-18 07:00:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 11,
    "RoundNumber": 2,
    "DateUtc": "2022-03-18 09:05:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 12,
    "RoundNumber": 2,
    "DateUtc": "2022-03-19 04:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 13,
    "RoundNumber": 2,
    "DateUtc": "2022-03-19 06:30:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 14,
    "RoundNumber": 2,
    "DateUtc": "2022-03-19 08:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 15,
    "RoundNumber": 2,
    "DateUtc": "2022-03-20 05:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 16,
    "RoundNumber": 2,
    "DateUtc": "2022-03-20 07:15:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 17,
    "RoundNumber": 3,
    "DateUtc": "2022-03-24 09:05:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 18,
    "RoundNumber": 3,
    "DateUtc": "2022-03-25 07:00:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 19,
    "RoundNumber": 3,
    "DateUtc": "2022-03-25 09:05:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 20,
    "RoundNumber": 3,
    "DateUtc": "2022-03-26 04:00:00Z",
    "Location": "Carrington Park",
    "HomeTeam": "Panthers",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 38,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 21,
    "RoundNumber": 3,
    "DateUtc": "2022-03-26 06:30:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 22,
    "RoundNumber": 3,
    "DateUtc": "2022-03-26 08:35:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 23,
    "RoundNumber": 3,
    "DateUtc": "2022-03-27 05:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 38
  },
  {
    "MatchNumber": 24,
    "RoundNumber": 3,
    "DateUtc": "2022-03-27 07:15:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 13,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 25,
    "RoundNumber": 4,
    "DateUtc": "2022-03-31 09:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 8,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 26,
    "RoundNumber": 4,
    "DateUtc": "2022-04-01 07:00:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 27,
    "RoundNumber": 4,
    "DateUtc": "2022-04-01 09:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 28,
    "RoundNumber": 4,
    "DateUtc": "2022-04-02 04:00:00Z",
    "Location": "Moreton Daily Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 29,
    "RoundNumber": 4,
    "DateUtc": "2022-04-02 06:30:00Z",
    "Location": "Glen Willow Oval",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 25,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 30,
    "RoundNumber": 4,
    "DateUtc": "2022-04-02 08:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 4,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 31,
    "RoundNumber": 4,
    "DateUtc": "2022-04-03 06:05:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 32,
    "RoundNumber": 4,
    "DateUtc": "2022-04-03 08:15:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 33,
    "RoundNumber": 5,
    "DateUtc": "2022-04-07 09:50:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 34,
    "RoundNumber": 5,
    "DateUtc": "2022-04-08 08:00:00Z",
    "Location": "Moreton Daily Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 25,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 35,
    "RoundNumber": 5,
    "DateUtc": "2022-04-08 09:55:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 36,
    "RoundNumber": 5,
    "DateUtc": "2022-04-09 05:00:00Z",
    "Location": "McDonalds Park",
    "HomeTeam": "Raiders",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 37,
    "RoundNumber": 5,
    "DateUtc": "2022-04-09 07:30:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 38,
    "RoundNumber": 5,
    "DateUtc": "2022-04-09 09:35:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 39,
    "RoundNumber": 5,
    "DateUtc": "2022-04-10 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 40,
    "RoundNumber": 5,
    "DateUtc": "2022-04-10 08:15:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 41,
    "RoundNumber": 6,
    "DateUtc": "2022-04-14 09:50:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 42,
    "RoundNumber": 6,
    "DateUtc": "2022-04-15 06:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 43,
    "RoundNumber": 6,
    "DateUtc": "2022-04-15 09:55:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 40,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 44,
    "RoundNumber": 6,
    "DateUtc": "2022-04-16 07:30:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 45,
    "RoundNumber": 6,
    "DateUtc": "2022-04-16 09:35:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 46,
    "RoundNumber": 6,
    "DateUtc": "2022-04-17 04:00:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 47,
    "RoundNumber": 6,
    "DateUtc": "2022-04-17 06:05:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 21,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 48,
    "RoundNumber": 6,
    "DateUtc": "2022-04-18 06:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 21
  },
  {
    "MatchNumber": 49,
    "RoundNumber": 7,
    "DateUtc": "2022-04-21 09:50:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 50,
    "RoundNumber": 7,
    "DateUtc": "2022-04-22 09:55:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 51,
    "RoundNumber": 7,
    "DateUtc": "2022-04-23 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 52,
    "RoundNumber": 7,
    "DateUtc": "2022-04-23 09:35:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 23,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 53,
    "RoundNumber": 7,
    "DateUtc": "2022-04-24 04:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 2,
    "AwayTeamScore": 39
  },
  {
    "MatchNumber": 54,
    "RoundNumber": 7,
    "DateUtc": "2022-04-24 06:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 55,
    "RoundNumber": 7,
    "DateUtc": "2022-04-25 06:00:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Dragons",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 56,
    "RoundNumber": 7,
    "DateUtc": "2022-04-25 09:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 70,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 57,
    "RoundNumber": 8,
    "DateUtc": "2022-04-28 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 7
  },
  {
    "MatchNumber": 58,
    "RoundNumber": 8,
    "DateUtc": "2022-04-29 08:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 4,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 59,
    "RoundNumber": 8,
    "DateUtc": "2022-04-29 09:55:00Z",
    "Location": "Central Coast Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 40,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 60,
    "RoundNumber": 8,
    "DateUtc": "2022-04-30 05:00:00Z",
    "Location": "Moreton Daily Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 21,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 61,
    "RoundNumber": 8,
    "DateUtc": "2022-04-30 07:30:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 62,
    "RoundNumber": 8,
    "DateUtc": "2022-04-30 09:35:00Z",
    "Location": "TIO Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 4,
    "AwayTeamScore": 35
  },
  {
    "MatchNumber": 63,
    "RoundNumber": 8,
    "DateUtc": "2022-05-01 04:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 2,
    "AwayTeamScore": 50
  },
  {
    "MatchNumber": 64,
    "RoundNumber": 8,
    "DateUtc": "2022-05-01 06:05:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 65,
    "RoundNumber": 9,
    "DateUtc": "2022-05-05 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 66,
    "RoundNumber": 9,
    "DateUtc": "2022-05-06 08:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 67,
    "RoundNumber": 9,
    "DateUtc": "2022-05-06 09:55:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 68,
    "RoundNumber": 9,
    "DateUtc": "2022-05-07 05:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 69,
    "RoundNumber": 9,
    "DateUtc": "2022-05-07 07:30:00Z",
    "Location": "BB Print Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 70,
    "RoundNumber": 9,
    "DateUtc": "2022-05-07 09:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 71,
    "RoundNumber": 9,
    "DateUtc": "2022-05-08 04:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 72,
    "RoundNumber": 9,
    "DateUtc": "2022-05-08 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 29,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 73,
    "RoundNumber": 10,
    "DateUtc": "2022-05-13 08:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 74,
    "RoundNumber": 10,
    "DateUtc": "2022-05-13 10:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 0,
    "AwayTeamScore": 38
  },
  {
    "MatchNumber": 75,
    "RoundNumber": 10,
    "DateUtc": "2022-05-14 05:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 76,
    "RoundNumber": 10,
    "DateUtc": "2022-05-14 07:30:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 77,
    "RoundNumber": 10,
    "DateUtc": "2022-05-14 09:45:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Storm",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 78,
    "RoundNumber": 10,
    "DateUtc": "2022-05-15 03:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 79,
    "RoundNumber": 10,
    "DateUtc": "2022-05-15 06:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 31,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 80,
    "RoundNumber": 10,
    "DateUtc": "2022-05-15 08:25:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 81,
    "RoundNumber": 11,
    "DateUtc": "2022-05-19 09:50:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 82,
    "RoundNumber": 11,
    "DateUtc": "2022-05-20 08:00:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 83,
    "RoundNumber": 11,
    "DateUtc": "2022-05-20 09:55:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 84,
    "RoundNumber": 11,
    "DateUtc": "2022-05-21 05:00:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 85,
    "RoundNumber": 11,
    "DateUtc": "2022-05-21 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 86,
    "RoundNumber": 11,
    "DateUtc": "2022-05-21 09:35:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 87,
    "RoundNumber": 11,
    "DateUtc": "2022-05-22 04:00:00Z",
    "Location": "Apex Oval",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 88,
    "RoundNumber": 11,
    "DateUtc": "2022-05-22 06:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 25
  },
  {
    "MatchNumber": 89,
    "RoundNumber": 12,
    "DateUtc": "2022-05-26 09:50:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 8
  },
  {
    "MatchNumber": 90,
    "RoundNumber": 12,
    "DateUtc": "2022-05-27 08:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 91,
    "RoundNumber": 12,
    "DateUtc": "2022-05-27 09:55:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 35,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 92,
    "RoundNumber": 12,
    "DateUtc": "2022-05-28 05:00:00Z",
    "Location": "Moreton Daily Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 93,
    "RoundNumber": 12,
    "DateUtc": "2022-05-28 07:30:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 94,
    "RoundNumber": 12,
    "DateUtc": "2022-05-28 09:35:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 95,
    "RoundNumber": 12,
    "DateUtc": "2022-05-29 04:00:00Z",
    "Location": "Belmore Sports Ground",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 96,
    "RoundNumber": 12,
    "DateUtc": "2022-05-29 06:05:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 97,
    "RoundNumber": 13,
    "DateUtc": "2022-06-02 09:50:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 98,
    "RoundNumber": 13,
    "DateUtc": "2022-06-03 09:55:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 99,
    "RoundNumber": 13,
    "DateUtc": "2022-06-04 09:35:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 100,
    "RoundNumber": 13,
    "DateUtc": "2022-06-05 06:05:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 101,
    "RoundNumber": 14,
    "DateUtc": "2022-06-10 09:55:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 31,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 102,
    "RoundNumber": 14,
    "DateUtc": "2022-06-11 05:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 103,
    "RoundNumber": 14,
    "DateUtc": "2022-06-11 07:30:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 104,
    "RoundNumber": 14,
    "DateUtc": "2022-06-11 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 105,
    "RoundNumber": 14,
    "DateUtc": "2022-06-12 04:00:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 4,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 106,
    "RoundNumber": 14,
    "DateUtc": "2022-06-12 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 42
  },
  {
    "MatchNumber": 107,
    "RoundNumber": 14,
    "DateUtc": "2022-06-12 08:15:00Z",
    "Location": "Moreton Daily Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 38
  },
  {
    "MatchNumber": 108,
    "RoundNumber": 14,
    "DateUtc": "2022-06-13 06:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 109,
    "RoundNumber": 15,
    "DateUtc": "2022-06-16 09:50:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 110,
    "RoundNumber": 15,
    "DateUtc": "2022-06-17 08:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 111,
    "RoundNumber": 15,
    "DateUtc": "2022-06-17 09:55:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 112,
    "RoundNumber": 15,
    "DateUtc": "2022-06-18 05:00:00Z",
    "Location": "C.ex Coffs International Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 113,
    "RoundNumber": 15,
    "DateUtc": "2022-06-18 07:30:00Z",
    "Location": "Moreton Daily Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 40
  },
  {
    "MatchNumber": 114,
    "RoundNumber": 15,
    "DateUtc": "2022-06-18 09:35:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 115,
    "RoundNumber": 15,
    "DateUtc": "2022-06-19 04:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 116,
    "RoundNumber": 15,
    "DateUtc": "2022-06-19 06:05:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 117,
    "RoundNumber": 16,
    "DateUtc": "2022-06-30 09:50:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 118,
    "RoundNumber": 16,
    "DateUtc": "2022-07-01 08:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 38,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 119,
    "RoundNumber": 16,
    "DateUtc": "2022-07-01 09:55:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 120,
    "RoundNumber": 16,
    "DateUtc": "2022-07-02 05:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 121,
    "RoundNumber": 16,
    "DateUtc": "2022-07-02 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 40,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 122,
    "RoundNumber": 16,
    "DateUtc": "2022-07-02 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 123,
    "RoundNumber": 16,
    "DateUtc": "2022-07-03 04:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 2
  },
  {
    "MatchNumber": 124,
    "RoundNumber": 16,
    "DateUtc": "2022-07-03 06:05:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 125,
    "RoundNumber": 17,
    "DateUtc": "2022-07-07 09:50:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 126,
    "RoundNumber": 17,
    "DateUtc": "2022-07-08 09:55:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 40
  },
  {
    "MatchNumber": 127,
    "RoundNumber": 17,
    "DateUtc": "2022-07-09 09:35:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 128,
    "RoundNumber": 17,
    "DateUtc": "2022-07-10 06:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 129,
    "RoundNumber": 18,
    "DateUtc": "2022-07-15 08:00:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 130,
    "RoundNumber": 18,
    "DateUtc": "2022-07-15 09:55:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 131,
    "RoundNumber": 18,
    "DateUtc": "2022-07-16 05:00:00Z",
    "Location": "Central Coast Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 54,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 132,
    "RoundNumber": 18,
    "DateUtc": "2022-07-16 07:30:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 133,
    "RoundNumber": 18,
    "DateUtc": "2022-07-16 09:35:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 134,
    "RoundNumber": 18,
    "DateUtc": "2022-07-17 04:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 135,
    "RoundNumber": 18,
    "DateUtc": "2022-07-17 06:05:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 136,
    "RoundNumber": 18,
    "DateUtc": "2022-07-17 08:15:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 137,
    "RoundNumber": 19,
    "DateUtc": "2022-07-21 09:50:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 138,
    "RoundNumber": 19,
    "DateUtc": "2022-07-22 08:00:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 139,
    "RoundNumber": 19,
    "DateUtc": "2022-07-22 09:55:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 42
  },
  {
    "MatchNumber": 140,
    "RoundNumber": 19,
    "DateUtc": "2022-07-23 05:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 141,
    "RoundNumber": 19,
    "DateUtc": "2022-07-23 07:30:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 142,
    "RoundNumber": 19,
    "DateUtc": "2022-07-23 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 143,
    "RoundNumber": 19,
    "DateUtc": "2022-07-24 04:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 144,
    "RoundNumber": 19,
    "DateUtc": "2022-07-24 06:05:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 27,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 145,
    "RoundNumber": 20,
    "DateUtc": "2022-07-28 09:50:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 146,
    "RoundNumber": 20,
    "DateUtc": "2022-07-29 08:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 147,
    "RoundNumber": 20,
    "DateUtc": "2022-07-29 09:55:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 148,
    "RoundNumber": 20,
    "DateUtc": "2022-07-30 05:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 149,
    "RoundNumber": 20,
    "DateUtc": "2022-07-30 07:30:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 21,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 150,
    "RoundNumber": 20,
    "DateUtc": "2022-07-30 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 151,
    "RoundNumber": 20,
    "DateUtc": "2022-07-31 04:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 152,
    "RoundNumber": 20,
    "DateUtc": "2022-07-31 06:05:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 8,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 153,
    "RoundNumber": 21,
    "DateUtc": "2022-08-04 09:50:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 154,
    "RoundNumber": 21,
    "DateUtc": "2022-08-05 08:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 155,
    "RoundNumber": 21,
    "DateUtc": "2022-08-05 09:55:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 156,
    "RoundNumber": 21,
    "DateUtc": "2022-08-06 05:00:00Z",
    "Location": "Sunshine Coast Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 157,
    "RoundNumber": 21,
    "DateUtc": "2022-08-06 07:30:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 158,
    "RoundNumber": 21,
    "DateUtc": "2022-08-06 09:35:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 159,
    "RoundNumber": 21,
    "DateUtc": "2022-08-07 04:00:00Z",
    "Location": "Salter Oval",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 160,
    "RoundNumber": 21,
    "DateUtc": "2022-08-07 06:05:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 161,
    "RoundNumber": 22,
    "DateUtc": "2022-08-11 09:50:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 0,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 162,
    "RoundNumber": 22,
    "DateUtc": "2022-08-12 08:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 163,
    "RoundNumber": 22,
    "DateUtc": "2022-08-12 09:55:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 0,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 164,
    "RoundNumber": 22,
    "DateUtc": "2022-08-13 05:00:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 165,
    "RoundNumber": 22,
    "DateUtc": "2022-08-13 07:30:00Z",
    "Location": "Scully Park",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 166,
    "RoundNumber": 22,
    "DateUtc": "2022-08-13 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 167,
    "RoundNumber": 22,
    "DateUtc": "2022-08-14 04:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 168,
    "RoundNumber": 22,
    "DateUtc": "2022-08-14 06:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 169,
    "RoundNumber": 23,
    "DateUtc": "2022-08-18 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 170,
    "RoundNumber": 23,
    "DateUtc": "2022-08-19 08:00:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 171,
    "RoundNumber": 23,
    "DateUtc": "2022-08-19 09:55:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 60
  },
  {
    "MatchNumber": 172,
    "RoundNumber": 23,
    "DateUtc": "2022-08-20 05:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 173,
    "RoundNumber": 23,
    "DateUtc": "2022-08-20 07:30:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 40
  },
  {
    "MatchNumber": 174,
    "RoundNumber": 23,
    "DateUtc": "2022-08-20 09:35:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 72,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 175,
    "RoundNumber": 23,
    "DateUtc": "2022-08-21 04:00:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 46,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 176,
    "RoundNumber": 23,
    "DateUtc": "2022-08-21 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 177,
    "RoundNumber": 24,
    "DateUtc": "2022-08-25 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 53
  },
  {
    "MatchNumber": 178,
    "RoundNumber": 24,
    "DateUtc": "2022-08-26 08:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 46,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 179,
    "RoundNumber": 24,
    "DateUtc": "2022-08-26 09:55:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 180,
    "RoundNumber": 24,
    "DateUtc": "2022-08-27 05:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 181,
    "RoundNumber": 24,
    "DateUtc": "2022-08-27 07:30:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 182,
    "RoundNumber": 24,
    "DateUtc": "2022-08-27 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 183,
    "RoundNumber": 24,
    "DateUtc": "2022-08-28 04:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 184,
    "RoundNumber": 24,
    "DateUtc": "2022-08-28 06:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 185,
    "RoundNumber": 25,
    "DateUtc": "2022-09-01 09:50:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 186,
    "RoundNumber": 25,
    "DateUtc": "2022-09-02 08:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 21,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 187,
    "RoundNumber": 25,
    "DateUtc": "2022-09-02 09:55:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 188,
    "RoundNumber": 25,
    "DateUtc": "2022-09-03 05:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 27
  },
  {
    "MatchNumber": 189,
    "RoundNumber": 25,
    "DateUtc": "2022-09-03 07:30:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 190,
    "RoundNumber": 25,
    "DateUtc": "2022-09-03 09:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 38,
    "AwayTeamScore": 8
  },
  {
    "MatchNumber": 191,
    "RoundNumber": 25,
    "DateUtc": "2022-09-04 04:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 38
  },
  {
    "MatchNumber": 192,
    "RoundNumber": 25,
    "DateUtc": "2022-09-04 06:05:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 56
  },
  {
    "MatchNumber": 193,
    "RoundNumber": 26,
    "DateUtc": "2022-09-09 09:50:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 27,
    "AwayTeamScore": 8
  },
  {
    "MatchNumber": 194,
    "RoundNumber": 26,
    "DateUtc": "2022-09-10 07:40:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 195,
    "RoundNumber": 26,
    "DateUtc": "2022-09-10 09:50:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 196,
    "RoundNumber": 26,
    "DateUtc": "2022-09-11 06:05:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 197,
    "RoundNumber": 27,
    "DateUtc": "2022-09-16 09:50:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 40,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 198,
    "RoundNumber": 27,
    "DateUtc": "2022-09-17 10:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 38
  },
  {
    "MatchNumber": 199,
    "RoundNumber": 28,
    "DateUtc": "2022-09-23 09:50:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 200,
    "RoundNumber": 28,
    "DateUtc": "2022-09-24 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 201,
    "RoundNumber": 29,
    "DateUtc": "2022-10-02 08:30:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 12
  }
];
