// TODO figure out a way to keep this mock code
// out of the produciton release to avoid code bloat
// e.g. if (!kReleaseMode) {

const mockNrl2024Full = [
  {
    "MatchNumber": 1,
    "RoundNumber": 1,
    "DateUtc": "2024-03-03 02:30:00Z",
    "Location": "Allegiant Stadium",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 2,
    "RoundNumber": 1,
    "DateUtc": "2024-03-03 04:30:00Z",
    "Location": "Allegiant Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 3,
    "RoundNumber": 1,
    "DateUtc": "2024-03-07 09:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 4,
    "RoundNumber": 1,
    "DateUtc": "2024-03-08 07:00:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 5,
    "RoundNumber": 1,
    "DateUtc": "2024-03-08 09:05:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 6,
    "RoundNumber": 1,
    "DateUtc": "2024-03-09 06:30:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 7,
    "RoundNumber": 1,
    "DateUtc": "2024-03-09 08:35:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 8,
    "RoundNumber": 1,
    "DateUtc": "2024-03-10 05:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 9,
    "RoundNumber": 2,
    "DateUtc": "2024-03-14 09:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 10,
    "RoundNumber": 2,
    "DateUtc": "2024-03-15 07:00:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 11,
    "RoundNumber": 2,
    "DateUtc": "2024-03-15 09:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 12,
    "RoundNumber": 2,
    "DateUtc": "2024-03-16 04:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 13,
    "RoundNumber": 2,
    "DateUtc": "2024-03-16 06:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 14,
    "RoundNumber": 2,
    "DateUtc": "2024-03-16 08:35:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 15,
    "RoundNumber": 2,
    "DateUtc": "2024-03-17 05:05:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 16,
    "RoundNumber": 2,
    "DateUtc": "2024-03-17 07:15:00Z",
    "Location": "Kayo Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 17,
    "RoundNumber": 3,
    "DateUtc": "2024-03-21 09:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 18,
    "RoundNumber": 3,
    "DateUtc": "2024-03-22 07:00:00Z",
    "Location": "Apollo Projects Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 19,
    "RoundNumber": 3,
    "DateUtc": "2024-03-22 09:05:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 20,
    "RoundNumber": 3,
    "DateUtc": "2024-03-23 04:00:00Z",
    "Location": "Belmore Sports Ground",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 21,
    "RoundNumber": 3,
    "DateUtc": "2024-03-23 06:30:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 22,
    "RoundNumber": 3,
    "DateUtc": "2024-03-23 08:35:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 23,
    "RoundNumber": 3,
    "DateUtc": "2024-03-24 05:05:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 24,
    "RoundNumber": 3,
    "DateUtc": "2024-03-24 07:15:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 25,
    "RoundNumber": 4,
    "DateUtc": "2024-03-28 09:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 26,
    "RoundNumber": 4,
    "DateUtc": "2024-03-29 05:05:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 27,
    "RoundNumber": 4,
    "DateUtc": "2024-03-29 09:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 28,
    "RoundNumber": 4,
    "DateUtc": "2024-03-30 06:30:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 29,
    "RoundNumber": 4,
    "DateUtc": "2024-03-30 08:35:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 30,
    "RoundNumber": 4,
    "DateUtc": "2024-03-31 05:05:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 31,
    "RoundNumber": 4,
    "DateUtc": "2024-03-31 07:15:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 32,
    "RoundNumber": 4,
    "DateUtc": "2024-04-01 05:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 33,
    "RoundNumber": 5,
    "DateUtc": "2024-04-04 09:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 34,
    "RoundNumber": 5,
    "DateUtc": "2024-04-05 07:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 35,
    "RoundNumber": 5,
    "DateUtc": "2024-04-05 09:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 36,
    "RoundNumber": 5,
    "DateUtc": "2024-04-06 04:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 37,
    "RoundNumber": 5,
    "DateUtc": "2024-04-06 06:30:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 38,
    "RoundNumber": 5,
    "DateUtc": "2024-04-06 08:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 39,
    "RoundNumber": 5,
    "DateUtc": "2024-04-07 06:05:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 40,
    "RoundNumber": 5,
    "DateUtc": "2024-04-07 08:15:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 41,
    "RoundNumber": 6,
    "DateUtc": "2024-04-11 09:50:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 42,
    "RoundNumber": 6,
    "DateUtc": "2024-04-12 08:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 43,
    "RoundNumber": 6,
    "DateUtc": "2024-04-12 10:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 44,
    "RoundNumber": 6,
    "DateUtc": "2024-04-13 05:00:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 45,
    "RoundNumber": 6,
    "DateUtc": "2024-04-13 07:30:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 46,
    "RoundNumber": 6,
    "DateUtc": "2024-04-13 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 47,
    "RoundNumber": 6,
    "DateUtc": "2024-04-14 06:05:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 48,
    "RoundNumber": 6,
    "DateUtc": "2024-04-14 08:15:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 49,
    "RoundNumber": 7,
    "DateUtc": "2024-04-18 09:50:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 50,
    "RoundNumber": 7,
    "DateUtc": "2024-04-19 08:00:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 51,
    "RoundNumber": 7,
    "DateUtc": "2024-04-19 10:00:00Z",
    "Location": "TIO Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 52,
    "RoundNumber": 7,
    "DateUtc": "2024-04-20 05:00:00Z",
    "Location": "Carrington Park",
    "HomeTeam": "Panthers",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 53,
    "RoundNumber": 7,
    "DateUtc": "2024-04-20 07:30:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 54,
    "RoundNumber": 7,
    "DateUtc": "2024-04-20 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 55,
    "RoundNumber": 7,
    "DateUtc": "2024-04-21 04:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 56,
    "RoundNumber": 7,
    "DateUtc": "2024-04-21 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 57,
    "RoundNumber": 8,
    "DateUtc": "2024-04-25 04:00:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 58,
    "RoundNumber": 8,
    "DateUtc": "2024-04-25 06:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 59,
    "RoundNumber": 8,
    "DateUtc": "2024-04-25 09:50:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 60,
    "RoundNumber": 8,
    "DateUtc": "2024-04-26 10:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 61,
    "RoundNumber": 8,
    "DateUtc": "2024-04-27 07:30:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 62,
    "RoundNumber": 8,
    "DateUtc": "2024-04-27 09:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 63,
    "RoundNumber": 8,
    "DateUtc": "2024-04-28 04:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 64,
    "RoundNumber": 8,
    "DateUtc": "2024-04-28 06:05:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 65,
    "RoundNumber": 9,
    "DateUtc": "2024-05-02 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 66,
    "RoundNumber": 9,
    "DateUtc": "2024-05-03 08:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 67,
    "RoundNumber": 9,
    "DateUtc": "2024-05-03 10:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 68,
    "RoundNumber": 9,
    "DateUtc": "2024-05-04 05:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 69,
    "RoundNumber": 9,
    "DateUtc": "2024-05-04 07:30:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 70,
    "RoundNumber": 9,
    "DateUtc": "2024-05-04 09:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 71,
    "RoundNumber": 9,
    "DateUtc": "2024-05-05 04:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 72,
    "RoundNumber": 9,
    "DateUtc": "2024-05-05 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 73,
    "RoundNumber": 10,
    "DateUtc": "2024-05-09 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 74,
    "RoundNumber": 10,
    "DateUtc": "2024-05-10 08:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 75,
    "RoundNumber": 10,
    "DateUtc": "2024-05-10 10:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 76,
    "RoundNumber": 10,
    "DateUtc": "2024-05-11 05:00:00Z",
    "Location": "Scully Park",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 77,
    "RoundNumber": 10,
    "DateUtc": "2024-05-11 07:30:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 78,
    "RoundNumber": 10,
    "DateUtc": "2024-05-11 09:35:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 79,
    "RoundNumber": 10,
    "DateUtc": "2024-05-12 04:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 80,
    "RoundNumber": 10,
    "DateUtc": "2024-05-12 06:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 81,
    "RoundNumber": 11,
    "DateUtc": "2024-05-17 08:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 82,
    "RoundNumber": 11,
    "DateUtc": "2024-05-17 10:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 83,
    "RoundNumber": 11,
    "DateUtc": "2024-05-18 05:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 84,
    "RoundNumber": 11,
    "DateUtc": "2024-05-18 07:30:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 85,
    "RoundNumber": 11,
    "DateUtc": "2024-05-18 09:45:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 86,
    "RoundNumber": 11,
    "DateUtc": "2024-05-19 03:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 87,
    "RoundNumber": 11,
    "DateUtc": "2024-05-19 06:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Storm",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 88,
    "RoundNumber": 11,
    "DateUtc": "2024-05-19 08:25:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 89,
    "RoundNumber": 12,
    "DateUtc": "2024-05-23 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 90,
    "RoundNumber": 12,
    "DateUtc": "2024-05-24 08:00:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 91,
    "RoundNumber": 12,
    "DateUtc": "2024-05-24 10:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 92,
    "RoundNumber": 12,
    "DateUtc": "2024-05-25 05:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 93,
    "RoundNumber": 12,
    "DateUtc": "2024-05-25 07:30:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 94,
    "RoundNumber": 12,
    "DateUtc": "2024-05-25 09:35:00Z",
    "Location": "TBA",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 95,
    "RoundNumber": 12,
    "DateUtc": "2024-05-26 04:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 96,
    "RoundNumber": 12,
    "DateUtc": "2024-05-26 06:05:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 97,
    "RoundNumber": 13,
    "DateUtc": "2024-05-30 09:50:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 98,
    "RoundNumber": 13,
    "DateUtc": "2024-05-31 10:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 99,
    "RoundNumber": 13,
    "DateUtc": "2024-06-01 07:30:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 100,
    "RoundNumber": 13,
    "DateUtc": "2024-06-01 09:35:00Z",
    "Location": "Kayo Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 101,
    "RoundNumber": 13,
    "DateUtc": "2024-06-02 06:05:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 102,
    "RoundNumber": 14,
    "DateUtc": "2024-06-07 10:00:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 103,
    "RoundNumber": 14,
    "DateUtc": "2024-06-08 05:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 104,
    "RoundNumber": 14,
    "DateUtc": "2024-06-08 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 105,
    "RoundNumber": 14,
    "DateUtc": "2024-06-08 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 106,
    "RoundNumber": 14,
    "DateUtc": "2024-06-09 04:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 107,
    "RoundNumber": 14,
    "DateUtc": "2024-06-09 06:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 108,
    "RoundNumber": 14,
    "DateUtc": "2024-06-10 06:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 109,
    "RoundNumber": 15,
    "DateUtc": "2024-06-13 09:50:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 110,
    "RoundNumber": 15,
    "DateUtc": "2024-06-14 08:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 111,
    "RoundNumber": 15,
    "DateUtc": "2024-06-14 10:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 112,
    "RoundNumber": 15,
    "DateUtc": "2024-06-15 05:00:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 113,
    "RoundNumber": 15,
    "DateUtc": "2024-06-15 07:30:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 114,
    "RoundNumber": 15,
    "DateUtc": "2024-06-15 09:35:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 115,
    "RoundNumber": 15,
    "DateUtc": "2024-06-16 04:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 116,
    "RoundNumber": 15,
    "DateUtc": "2024-06-16 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 117,
    "RoundNumber": 16,
    "DateUtc": "2024-06-21 10:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 118,
    "RoundNumber": 16,
    "DateUtc": "2024-06-22 05:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 119,
    "RoundNumber": 16,
    "DateUtc": "2024-06-22 07:30:00Z",
    "Location": "Industree Group Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 120,
    "RoundNumber": 16,
    "DateUtc": "2024-06-22 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 121,
    "RoundNumber": 16,
    "DateUtc": "2024-06-23 06:05:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 122,
    "RoundNumber": 17,
    "DateUtc": "2024-06-28 10:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 123,
    "RoundNumber": 17,
    "DateUtc": "2024-06-29 05:00:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 124,
    "RoundNumber": 17,
    "DateUtc": "2024-06-29 07:30:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 125,
    "RoundNumber": 17,
    "DateUtc": "2024-06-29 09:35:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 126,
    "RoundNumber": 17,
    "DateUtc": "2024-06-30 04:00:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 127,
    "RoundNumber": 17,
    "DateUtc": "2024-06-30 06:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 128,
    "RoundNumber": 17,
    "DateUtc": "2024-06-30 08:15:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 129,
    "RoundNumber": 18,
    "DateUtc": "2024-07-04 09:50:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 130,
    "RoundNumber": 18,
    "DateUtc": "2024-07-05 08:00:00Z",
    "Location": "C.ex Coffs International Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 131,
    "RoundNumber": 18,
    "DateUtc": "2024-07-05 10:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 132,
    "RoundNumber": 18,
    "DateUtc": "2024-07-06 05:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 133,
    "RoundNumber": 18,
    "DateUtc": "2024-07-06 07:30:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 134,
    "RoundNumber": 18,
    "DateUtc": "2024-07-06 09:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 135,
    "RoundNumber": 18,
    "DateUtc": "2024-07-07 04:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 136,
    "RoundNumber": 18,
    "DateUtc": "2024-07-07 06:05:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 137,
    "RoundNumber": 19,
    "DateUtc": "2024-07-11 09:50:00Z",
    "Location": "Kayo Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 138,
    "RoundNumber": 19,
    "DateUtc": "2024-07-12 10:00:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 139,
    "RoundNumber": 19,
    "DateUtc": "2024-07-13 07:30:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 140,
    "RoundNumber": 19,
    "DateUtc": "2024-07-13 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 141,
    "RoundNumber": 19,
    "DateUtc": "2024-07-14 06:05:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 142,
    "RoundNumber": 20,
    "DateUtc": "2024-07-19 10:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 143,
    "RoundNumber": 20,
    "DateUtc": "2024-07-20 05:00:00Z",
    "Location": "Industree Group Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 144,
    "RoundNumber": 20,
    "DateUtc": "2024-07-20 07:30:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 145,
    "RoundNumber": 20,
    "DateUtc": "2024-07-20 09:35:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 146,
    "RoundNumber": 20,
    "DateUtc": "2024-07-21 04:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 147,
    "RoundNumber": 20,
    "DateUtc": "2024-07-21 06:05:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 148,
    "RoundNumber": 20,
    "DateUtc": "2024-07-21 08:15:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 149,
    "RoundNumber": 21,
    "DateUtc": "2024-07-26 08:00:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 150,
    "RoundNumber": 21,
    "DateUtc": "2024-07-26 10:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 151,
    "RoundNumber": 21,
    "DateUtc": "2024-07-27 05:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 152,
    "RoundNumber": 21,
    "DateUtc": "2024-07-27 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 153,
    "RoundNumber": 21,
    "DateUtc": "2024-07-27 09:35:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 154,
    "RoundNumber": 21,
    "DateUtc": "2024-07-28 04:00:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 155,
    "RoundNumber": 21,
    "DateUtc": "2024-07-28 06:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 156,
    "RoundNumber": 21,
    "DateUtc": "2024-07-28 08:15:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 157,
    "RoundNumber": 22,
    "DateUtc": "2024-08-01 09:50:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 158,
    "RoundNumber": 22,
    "DateUtc": "2024-08-02 08:00:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 159,
    "RoundNumber": 22,
    "DateUtc": "2024-08-02 10:00:00Z",
    "Location": "HBF Park",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 160,
    "RoundNumber": 22,
    "DateUtc": "2024-08-03 05:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 161,
    "RoundNumber": 22,
    "DateUtc": "2024-08-03 07:30:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 162,
    "RoundNumber": 22,
    "DateUtc": "2024-08-03 09:35:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 163,
    "RoundNumber": 22,
    "DateUtc": "2024-08-04 04:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 164,
    "RoundNumber": 22,
    "DateUtc": "2024-08-04 06:05:00Z",
    "Location": "Belmore Sports Ground",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 165,
    "RoundNumber": 23,
    "DateUtc": "2024-08-08 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 166,
    "RoundNumber": 23,
    "DateUtc": "2024-08-09 08:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 167,
    "RoundNumber": 23,
    "DateUtc": "2024-08-09 10:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 168,
    "RoundNumber": 23,
    "DateUtc": "2024-08-10 05:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 169,
    "RoundNumber": 23,
    "DateUtc": "2024-08-10 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 170,
    "RoundNumber": 23,
    "DateUtc": "2024-08-10 09:35:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 171,
    "RoundNumber": 23,
    "DateUtc": "2024-08-11 04:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 172,
    "RoundNumber": 23,
    "DateUtc": "2024-08-11 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 173,
    "RoundNumber": 24,
    "DateUtc": "2024-08-15 09:50:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 174,
    "RoundNumber": 24,
    "DateUtc": "2024-08-16 08:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 175,
    "RoundNumber": 24,
    "DateUtc": "2024-08-16 10:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 176,
    "RoundNumber": 24,
    "DateUtc": "2024-08-17 05:00:00Z",
    "Location": "Salter Oval",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 177,
    "RoundNumber": 24,
    "DateUtc": "2024-08-17 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 178,
    "RoundNumber": 24,
    "DateUtc": "2024-08-17 09:35:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 179,
    "RoundNumber": 24,
    "DateUtc": "2024-08-18 04:00:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 180,
    "RoundNumber": 24,
    "DateUtc": "2024-08-18 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 181,
    "RoundNumber": 25,
    "DateUtc": "2024-08-22 09:50:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 182,
    "RoundNumber": 25,
    "DateUtc": "2024-08-23 08:00:00Z",
    "Location": "Go Media Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 183,
    "RoundNumber": 25,
    "DateUtc": "2024-08-23 10:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 184,
    "RoundNumber": 25,
    "DateUtc": "2024-08-24 05:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 185,
    "RoundNumber": 25,
    "DateUtc": "2024-08-24 07:30:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 186,
    "RoundNumber": 25,
    "DateUtc": "2024-08-24 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 187,
    "RoundNumber": 25,
    "DateUtc": "2024-08-25 04:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 188,
    "RoundNumber": 25,
    "DateUtc": "2024-08-25 06:05:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 189,
    "RoundNumber": 26,
    "DateUtc": "2024-08-29 09:50:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 190,
    "RoundNumber": 26,
    "DateUtc": "2024-08-30 08:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 191,
    "RoundNumber": 26,
    "DateUtc": "2024-08-30 10:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 192,
    "RoundNumber": 26,
    "DateUtc": "2024-08-31 05:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 193,
    "RoundNumber": 26,
    "DateUtc": "2024-08-31 07:30:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 194,
    "RoundNumber": 26,
    "DateUtc": "2024-08-31 09:35:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 195,
    "RoundNumber": 26,
    "DateUtc": "2024-09-01 04:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 196,
    "RoundNumber": 26,
    "DateUtc": "2024-09-01 06:05:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 197,
    "RoundNumber": 27,
    "DateUtc": "2024-09-05 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 198,
    "RoundNumber": 27,
    "DateUtc": "2024-09-06 08:00:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 199,
    "RoundNumber": 27,
    "DateUtc": "2024-09-06 10:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 200,
    "RoundNumber": 27,
    "DateUtc": "2024-09-07 05:00:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 201,
    "RoundNumber": 27,
    "DateUtc": "2024-09-07 07:30:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 202,
    "RoundNumber": 27,
    "DateUtc": "2024-09-07 09:35:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 203,
    "RoundNumber": 27,
    "DateUtc": "2024-09-08 04:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  },
  {
    "MatchNumber": 204,
    "RoundNumber": 27,
    "DateUtc": "2024-09-08 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": null,
    "AwayTeamScore": null
  }
];
