// TODO figure out a way to keep this mock code
// out of the produciton release to avoid code bloat
// e.g. if (!kReleaseMode) {

const mockAfl2023Partial = [
  {
    "MatchNumber": 1,
    "RoundNumber": 1,
    "DateUtc": "2023-03-16 08:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 58,
    "AwayTeamScore": 58
  }
];

const mockAfl2023Full = [
  {
    "MatchNumber": 1,
    "RoundNumber": 1,
    "DateUtc": "2023-03-16 08:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 58,
    "AwayTeamScore": 58
  },
  {
    "MatchNumber": 2,
    "RoundNumber": 1,
    "DateUtc": "2023-03-17 08:40:00Z",
    "Location": "MCG",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 103,
    "AwayTeamScore": 125
  },
  {
    "MatchNumber": 3,
    "RoundNumber": 1,
    "DateUtc": "2023-03-18 02:45:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 87,
    "AwayTeamScore": 82
  },
  {
    "MatchNumber": 4,
    "RoundNumber": 1,
    "DateUtc": "2023-03-18 05:35:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 126,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 5,
    "RoundNumber": 1,
    "DateUtc": "2023-03-18 08:25:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 115,
    "AwayTeamScore": 65
  },
  {
    "MatchNumber": 6,
    "RoundNumber": 1,
    "DateUtc": "2023-03-18 09:00:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 61,
    "AwayTeamScore": 110
  },
  {
    "MatchNumber": 7,
    "RoundNumber": 1,
    "DateUtc": "2023-03-19 02:10:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 106,
    "AwayTeamScore": 90
  },
  {
    "MatchNumber": 8,
    "RoundNumber": 1,
    "DateUtc": "2023-03-19 04:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 65,
    "AwayTeamScore": 124
  },
  {
    "MatchNumber": 9,
    "RoundNumber": 1,
    "DateUtc": "2023-03-19 05:40:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 67,
    "AwayTeamScore": 52
  },
  {
    "MatchNumber": 10,
    "RoundNumber": 2,
    "DateUtc": "2023-03-23 08:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Carlton",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 90,
    "AwayTeamScore": 82
  },
  {
    "MatchNumber": 11,
    "RoundNumber": 2,
    "DateUtc": "2023-03-24 08:55:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 93,
    "AwayTeamScore": 82
  },
  {
    "MatchNumber": 12,
    "RoundNumber": 2,
    "DateUtc": "2023-03-25 02:45:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 135,
    "AwayTeamScore": 64
  },
  {
    "MatchNumber": 13,
    "RoundNumber": 2,
    "DateUtc": "2023-03-25 05:35:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 76,
    "AwayTeamScore": 108
  },
  {
    "MatchNumber": 14,
    "RoundNumber": 2,
    "DateUtc": "2023-03-25 08:25:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 41,
    "AwayTeamScore": 92
  },
  {
    "MatchNumber": 15,
    "RoundNumber": 2,
    "DateUtc": "2023-03-25 08:30:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 72,
    "AwayTeamScore": 73
  },
  {
    "MatchNumber": 16,
    "RoundNumber": 2,
    "DateUtc": "2023-03-26 02:10:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 118,
    "AwayTeamScore": 37
  },
  {
    "MatchNumber": 17,
    "RoundNumber": 2,
    "DateUtc": "2023-03-26 04:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Essendon",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 108,
    "AwayTeamScore": 80
  },
  {
    "MatchNumber": 18,
    "RoundNumber": 2,
    "DateUtc": "2023-03-26 07:20:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 100,
    "AwayTeamScore": 81
  },
  {
    "MatchNumber": 19,
    "RoundNumber": 3,
    "DateUtc": "2023-03-30 08:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 67,
    "AwayTeamScore": 53
  },
  {
    "MatchNumber": 20,
    "RoundNumber": 3,
    "DateUtc": "2023-03-31 08:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 63,
    "AwayTeamScore": 49
  },
  {
    "MatchNumber": 21,
    "RoundNumber": 3,
    "DateUtc": "2023-04-01 02:45:00Z",
    "Location": "University of Tasmania Stadium",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 80,
    "AwayTeamScore": 61
  },
  {
    "MatchNumber": 22,
    "RoundNumber": 3,
    "DateUtc": "2023-04-01 05:35:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 64,
    "AwayTeamScore": 74
  },
  {
    "MatchNumber": 23,
    "RoundNumber": 3,
    "DateUtc": "2023-04-01 08:25:00Z",
    "Location": "MCG",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 92,
    "AwayTeamScore": 74
  },
  {
    "MatchNumber": 24,
    "RoundNumber": 3,
    "DateUtc": "2023-04-01 08:30:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 86,
    "AwayTeamScore": 117
  },
  {
    "MatchNumber": 25,
    "RoundNumber": 3,
    "DateUtc": "2023-04-02 04:10:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 73,
    "AwayTeamScore": 54
  },
  {
    "MatchNumber": 26,
    "RoundNumber": 3,
    "DateUtc": "2023-04-02 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 135,
    "AwayTeamScore": 84
  },
  {
    "MatchNumber": 27,
    "RoundNumber": 3,
    "DateUtc": "2023-04-02 07:20:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 108,
    "AwayTeamScore": 67
  },
  {
    "MatchNumber": 28,
    "RoundNumber": 4,
    "DateUtc": "2023-04-06 09:35:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 116,
    "AwayTeamScore": 83
  },
  {
    "MatchNumber": 29,
    "RoundNumber": 4,
    "DateUtc": "2023-04-07 06:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 84,
    "AwayTeamScore": 107
  },
  {
    "MatchNumber": 30,
    "RoundNumber": 4,
    "DateUtc": "2023-04-08 03:45:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 111,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 31,
    "RoundNumber": 4,
    "DateUtc": "2023-04-08 06:35:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 84,
    "AwayTeamScore": 89
  },
  {
    "MatchNumber": 32,
    "RoundNumber": 4,
    "DateUtc": "2023-04-08 09:30:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 113,
    "AwayTeamScore": 60
  },
  {
    "MatchNumber": 33,
    "RoundNumber": 4,
    "DateUtc": "2023-04-08 09:30:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 64,
    "AwayTeamScore": 66
  },
  {
    "MatchNumber": 34,
    "RoundNumber": 4,
    "DateUtc": "2023-04-09 04:10:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Essendon",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 88,
    "AwayTeamScore": 75
  },
  {
    "MatchNumber": 35,
    "RoundNumber": 4,
    "DateUtc": "2023-04-09 07:20:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 63,
    "AwayTeamScore": 126
  },
  {
    "MatchNumber": 36,
    "RoundNumber": 4,
    "DateUtc": "2023-04-10 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 127,
    "AwayTeamScore": 45
  },
  {
    "MatchNumber": 37,
    "RoundNumber": 5,
    "DateUtc": "2023-04-13 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 118,
    "AwayTeamScore": 62
  },
  {
    "MatchNumber": 38,
    "RoundNumber": 5,
    "DateUtc": "2023-04-14 07:10:00Z",
    "Location": "Norwood Oval",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 100,
    "AwayTeamScore": 90
  },
  {
    "MatchNumber": 39,
    "RoundNumber": 5,
    "DateUtc": "2023-04-14 10:10:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Richmond",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 78,
    "AwayTeamScore": 122
  },
  {
    "MatchNumber": 40,
    "RoundNumber": 5,
    "DateUtc": "2023-04-15 03:10:00Z",
    "Location": "Adelaide Hills",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 152,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 41,
    "RoundNumber": 5,
    "DateUtc": "2023-04-15 06:10:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Essendon",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 104,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 42,
    "RoundNumber": 5,
    "DateUtc": "2023-04-15 09:50:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 70,
    "AwayTeamScore": 56
  },
  {
    "MatchNumber": 43,
    "RoundNumber": 5,
    "DateUtc": "2023-04-16 03:10:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 136,
    "AwayTeamScore": 89
  },
  {
    "MatchNumber": 44,
    "RoundNumber": 5,
    "DateUtc": "2023-04-16 05:20:00Z",
    "Location": "Norwood Oval",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 75
  },
  {
    "MatchNumber": 45,
    "RoundNumber": 5,
    "DateUtc": "2023-04-16 06:50:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Collingwood",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 70,
    "AwayTeamScore": 64
  },
  {
    "MatchNumber": 46,
    "RoundNumber": 6,
    "DateUtc": "2023-04-21 10:10:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 69,
    "AwayTeamScore": 118
  },
  {
    "MatchNumber": 47,
    "RoundNumber": 6,
    "DateUtc": "2023-04-22 03:45:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 109,
    "AwayTeamScore": 69
  },
  {
    "MatchNumber": 48,
    "RoundNumber": 6,
    "DateUtc": "2023-04-22 06:35:00Z",
    "Location": "Manuka Oval",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 87,
    "AwayTeamScore": 108
  },
  {
    "MatchNumber": 49,
    "RoundNumber": 6,
    "DateUtc": "2023-04-22 09:25:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 130,
    "AwayTeamScore": 37
  },
  {
    "MatchNumber": 50,
    "RoundNumber": 6,
    "DateUtc": "2023-04-23 03:10:00Z",
    "Location": "University of Tasmania Stadium",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 76,
    "AwayTeamScore": 79
  },
  {
    "MatchNumber": 51,
    "RoundNumber": 6,
    "DateUtc": "2023-04-23 05:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Carlton",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 60,
    "AwayTeamScore": 82
  },
  {
    "MatchNumber": 52,
    "RoundNumber": 6,
    "DateUtc": "2023-04-23 06:40:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 97,
    "AwayTeamScore": 54
  },
  {
    "MatchNumber": 53,
    "RoundNumber": 6,
    "DateUtc": "2023-04-24 09:25:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 96,
    "AwayTeamScore": 78
  },
  {
    "MatchNumber": 54,
    "RoundNumber": 6,
    "DateUtc": "2023-04-25 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 90,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 55,
    "RoundNumber": 7,
    "DateUtc": "2023-04-28 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 76,
    "AwayTeamScore": 83
  },
  {
    "MatchNumber": 56,
    "RoundNumber": 7,
    "DateUtc": "2023-04-29 03:45:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 115,
    "AwayTeamScore": 67
  },
  {
    "MatchNumber": 57,
    "RoundNumber": 7,
    "DateUtc": "2023-04-29 04:10:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 106,
    "AwayTeamScore": 107
  },
  {
    "MatchNumber": 58,
    "RoundNumber": 7,
    "DateUtc": "2023-04-29 06:35:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 94,
    "AwayTeamScore": 65
  },
  {
    "MatchNumber": 59,
    "RoundNumber": 7,
    "DateUtc": "2023-04-29 09:25:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 139,
    "AwayTeamScore": 49
  },
  {
    "MatchNumber": 60,
    "RoundNumber": 7,
    "DateUtc": "2023-04-29 09:30:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 153
  },
  {
    "MatchNumber": 61,
    "RoundNumber": 7,
    "DateUtc": "2023-04-30 03:10:00Z",
    "Location": "MCG",
    "HomeTeam": "Essendon",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 104,
    "AwayTeamScore": 132
  },
  {
    "MatchNumber": 62,
    "RoundNumber": 7,
    "DateUtc": "2023-04-30 05:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Richmond",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 63,
    "RoundNumber": 7,
    "DateUtc": "2023-04-30 06:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 58,
    "AwayTeamScore": 59
  },
  {
    "MatchNumber": 64,
    "RoundNumber": 8,
    "DateUtc": "2023-05-05 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Carlton",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 74,
    "AwayTeamScore": 100
  },
  {
    "MatchNumber": 65,
    "RoundNumber": 8,
    "DateUtc": "2023-05-06 03:45:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 104,
    "AwayTeamScore": 58
  },
  {
    "MatchNumber": 66,
    "RoundNumber": 8,
    "DateUtc": "2023-05-06 04:10:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 98,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 67,
    "RoundNumber": 8,
    "DateUtc": "2023-05-06 06:35:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 85,
    "AwayTeamScore": 90
  },
  {
    "MatchNumber": 68,
    "RoundNumber": 8,
    "DateUtc": "2023-05-06 09:30:00Z",
    "Location": "Manuka Oval",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 71,
    "AwayTeamScore": 86
  },
  {
    "MatchNumber": 69,
    "RoundNumber": 8,
    "DateUtc": "2023-05-06 09:30:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 117,
    "AwayTeamScore": 48
  },
  {
    "MatchNumber": 70,
    "RoundNumber": 8,
    "DateUtc": "2023-05-07 03:10:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 92,
    "AwayTeamScore": 87
  },
  {
    "MatchNumber": 71,
    "RoundNumber": 8,
    "DateUtc": "2023-05-07 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 48
  },
  {
    "MatchNumber": 72,
    "RoundNumber": 8,
    "DateUtc": "2023-05-07 06:40:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 64
  },
  {
    "MatchNumber": 73,
    "RoundNumber": 9,
    "DateUtc": "2023-05-12 09:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 102,
    "AwayTeamScore": 78
  },
  {
    "MatchNumber": 74,
    "RoundNumber": 9,
    "DateUtc": "2023-05-12 10:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 43,
    "AwayTeamScore": 113
  },
  {
    "MatchNumber": 75,
    "RoundNumber": 9,
    "DateUtc": "2023-05-13 03:45:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 86,
    "AwayTeamScore": 103
  },
  {
    "MatchNumber": 76,
    "RoundNumber": 9,
    "DateUtc": "2023-05-13 04:10:00Z",
    "Location": "Blundstone Arena",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 65,
    "AwayTeamScore": 135
  },
  {
    "MatchNumber": 77,
    "RoundNumber": 9,
    "DateUtc": "2023-05-13 06:35:00Z",
    "Location": "MCG",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 49,
    "AwayTeamScore": 103
  },
  {
    "MatchNumber": 78,
    "RoundNumber": 9,
    "DateUtc": "2023-05-13 09:25:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 87,
    "AwayTeamScore": 45
  },
  {
    "MatchNumber": 79,
    "RoundNumber": 9,
    "DateUtc": "2023-05-13 09:30:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Carlton",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 59,
    "AwayTeamScore": 79
  },
  {
    "MatchNumber": 80,
    "RoundNumber": 9,
    "DateUtc": "2023-05-14 03:10:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 121,
    "AwayTeamScore": 69
  },
  {
    "MatchNumber": 81,
    "RoundNumber": 9,
    "DateUtc": "2023-05-14 06:40:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 120,
    "AwayTeamScore": 55
  },
  {
    "MatchNumber": 82,
    "RoundNumber": 10,
    "DateUtc": "2023-05-19 09:50:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 80,
    "AwayTeamScore": 76
  },
  {
    "MatchNumber": 83,
    "RoundNumber": 10,
    "DateUtc": "2023-05-20 03:45:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 90,
    "AwayTeamScore": 93
  },
  {
    "MatchNumber": 84,
    "RoundNumber": 10,
    "DateUtc": "2023-05-20 04:10:00Z",
    "Location": "Mars Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 85,
    "AwayTeamScore": 40
  },
  {
    "MatchNumber": 85,
    "RoundNumber": 10,
    "DateUtc": "2023-05-20 06:35:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 106,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 86,
    "RoundNumber": 10,
    "DateUtc": "2023-05-20 09:30:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 107,
    "AwayTeamScore": 64
  },
  {
    "MatchNumber": 87,
    "RoundNumber": 10,
    "DateUtc": "2023-05-20 09:40:00Z",
    "Location": "MCG",
    "HomeTeam": "Essendon",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 71,
    "AwayTeamScore": 70
  },
  {
    "MatchNumber": 88,
    "RoundNumber": 10,
    "DateUtc": "2023-05-21 03:10:00Z",
    "Location": "University of Tasmania Stadium",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 142,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 89,
    "RoundNumber": 10,
    "DateUtc": "2023-05-21 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Carlton",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 57,
    "AwayTeamScore": 85
  },
  {
    "MatchNumber": 90,
    "RoundNumber": 10,
    "DateUtc": "2023-05-21 06:40:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 80,
    "AwayTeamScore": 92
  },
  {
    "MatchNumber": 91,
    "RoundNumber": 11,
    "DateUtc": "2023-05-26 09:50:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 51
  },
  {
    "MatchNumber": 92,
    "RoundNumber": 11,
    "DateUtc": "2023-05-27 03:45:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 78,
    "AwayTeamScore": 88
  },
  {
    "MatchNumber": 93,
    "RoundNumber": 11,
    "DateUtc": "2023-05-27 04:10:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 72,
    "AwayTeamScore": 79
  },
  {
    "MatchNumber": 94,
    "RoundNumber": 11,
    "DateUtc": "2023-05-27 06:35:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 74,
    "AwayTeamScore": 81
  },
  {
    "MatchNumber": 95,
    "RoundNumber": 11,
    "DateUtc": "2023-05-27 09:25:00Z",
    "Location": "TIO Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 84,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 96,
    "RoundNumber": 11,
    "DateUtc": "2023-05-27 09:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 46,
    "AwayTeamScore": 96
  },
  {
    "MatchNumber": 97,
    "RoundNumber": 11,
    "DateUtc": "2023-05-28 03:10:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 67,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 98,
    "RoundNumber": 11,
    "DateUtc": "2023-05-28 05:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Collingwood",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 105,
    "AwayTeamScore": 70
  },
  {
    "MatchNumber": 99,
    "RoundNumber": 11,
    "DateUtc": "2023-05-28 06:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 95,
    "AwayTeamScore": 78
  },
  {
    "MatchNumber": 100,
    "RoundNumber": 12,
    "DateUtc": "2023-06-02 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 61,
    "AwayTeamScore": 44
  },
  {
    "MatchNumber": 101,
    "RoundNumber": 12,
    "DateUtc": "2023-06-03 03:45:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 151,
    "AwayTeamScore": 96
  },
  {
    "MatchNumber": 102,
    "RoundNumber": 12,
    "DateUtc": "2023-06-03 06:35:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 57,
    "AwayTeamScore": 120
  },
  {
    "MatchNumber": 103,
    "RoundNumber": 12,
    "DateUtc": "2023-06-03 09:25:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 75,
    "AwayTeamScore": 97
  },
  {
    "MatchNumber": 104,
    "RoundNumber": 12,
    "DateUtc": "2023-06-03 09:30:00Z",
    "Location": "TIO Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 112,
    "AwayTeamScore": 87
  },
  {
    "MatchNumber": 105,
    "RoundNumber": 12,
    "DateUtc": "2023-06-04 03:10:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 104,
    "AwayTeamScore": 110
  },
  {
    "MatchNumber": 106,
    "RoundNumber": 12,
    "DateUtc": "2023-06-04 06:40:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Essendon",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 105,
    "AwayTeamScore": 99
  },
  {
    "MatchNumber": 107,
    "RoundNumber": 13,
    "DateUtc": "2023-06-08 09:10:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 66,
    "AwayTeamScore": 80
  },
  {
    "MatchNumber": 108,
    "RoundNumber": 13,
    "DateUtc": "2023-06-09 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 85,
    "AwayTeamScore": 107
  },
  {
    "MatchNumber": 109,
    "RoundNumber": 13,
    "DateUtc": "2023-06-10 03:45:00Z",
    "Location": "MCG",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 98,
    "AwayTeamScore": 73
  },
  {
    "MatchNumber": 110,
    "RoundNumber": 13,
    "DateUtc": "2023-06-10 06:35:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 174,
    "AwayTeamScore": 52
  },
  {
    "MatchNumber": 111,
    "RoundNumber": 13,
    "DateUtc": "2023-06-10 09:25:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 70,
    "AwayTeamScore": 85
  },
  {
    "MatchNumber": 112,
    "RoundNumber": 13,
    "DateUtc": "2023-06-11 05:20:00Z",
    "Location": "Blundstone Arena",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 75,
    "AwayTeamScore": 103
  },
  {
    "MatchNumber": 113,
    "RoundNumber": 13,
    "DateUtc": "2023-06-11 09:15:00Z",
    "Location": "MCG",
    "HomeTeam": "Carlton",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 52,
    "AwayTeamScore": 86
  },
  {
    "MatchNumber": 114,
    "RoundNumber": 13,
    "DateUtc": "2023-06-12 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 66,
    "AwayTeamScore": 62
  },
  {
    "MatchNumber": 115,
    "RoundNumber": 14,
    "DateUtc": "2023-06-15 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 110,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 116,
    "RoundNumber": 14,
    "DateUtc": "2023-06-16 09:50:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 97,
    "AwayTeamScore": 81
  },
  {
    "MatchNumber": 117,
    "RoundNumber": 14,
    "DateUtc": "2023-06-17 06:35:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 106,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 118,
    "RoundNumber": 14,
    "DateUtc": "2023-06-17 09:25:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 90,
    "AwayTeamScore": 70
  },
  {
    "MatchNumber": 119,
    "RoundNumber": 14,
    "DateUtc": "2023-06-18 03:10:00Z",
    "Location": "MCG",
    "HomeTeam": "Carlton",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 120,
    "AwayTeamScore": 61
  },
  {
    "MatchNumber": 120,
    "RoundNumber": 14,
    "DateUtc": "2023-06-18 06:40:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 84,
    "AwayTeamScore": 105
  },
  {
    "MatchNumber": 121,
    "RoundNumber": 15,
    "DateUtc": "2023-06-22 09:20:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 78,
    "AwayTeamScore": 63
  },
  {
    "MatchNumber": 122,
    "RoundNumber": 15,
    "DateUtc": "2023-06-23 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 56,
    "AwayTeamScore": 84
  },
  {
    "MatchNumber": 123,
    "RoundNumber": 15,
    "DateUtc": "2023-06-24 06:35:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 205,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 124,
    "RoundNumber": 15,
    "DateUtc": "2023-06-24 09:25:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 93,
    "AwayTeamScore": 61
  },
  {
    "MatchNumber": 125,
    "RoundNumber": 15,
    "DateUtc": "2023-06-25 03:10:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 82,
    "AwayTeamScore": 80
  },
  {
    "MatchNumber": 126,
    "RoundNumber": 15,
    "DateUtc": "2023-06-25 06:40:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 101,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 127,
    "RoundNumber": 16,
    "DateUtc": "2023-06-29 09:20:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 134,
    "AwayTeamScore": 53
  },
  {
    "MatchNumber": 131,
    "RoundNumber": 16,
    "DateUtc": "2023-06-30 09:50:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 54,
    "AwayTeamScore": 54
  },
  {
    "MatchNumber": 132,
    "RoundNumber": 16,
    "DateUtc": "2023-07-01 03:45:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 102,
    "AwayTeamScore": 73
  },
  {
    "MatchNumber": 133,
    "RoundNumber": 16,
    "DateUtc": "2023-07-01 03:45:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 138,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 129,
    "RoundNumber": 16,
    "DateUtc": "2023-07-01 06:35:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 120
  },
  {
    "MatchNumber": 128,
    "RoundNumber": 16,
    "DateUtc": "2023-07-01 09:25:00Z",
    "Location": "MCG",
    "HomeTeam": "Essendon",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 74,
    "AwayTeamScore": 78
  },
  {
    "MatchNumber": 130,
    "RoundNumber": 16,
    "DateUtc": "2023-07-02 03:10:00Z",
    "Location": "MCG",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 52,
    "AwayTeamScore": 112
  },
  {
    "MatchNumber": 134,
    "RoundNumber": 16,
    "DateUtc": "2023-07-02 05:20:00Z",
    "Location": "TIO Traeger Park",
    "HomeTeam": "Melbourne",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 45,
    "AwayTeamScore": 47
  },
  {
    "MatchNumber": 135,
    "RoundNumber": 16,
    "DateUtc": "2023-07-02 06:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 85
  },
  {
    "MatchNumber": 140,
    "RoundNumber": 17,
    "DateUtc": "2023-07-06 09:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 88,
    "AwayTeamScore": 75
  },
  {
    "MatchNumber": 142,
    "RoundNumber": 17,
    "DateUtc": "2023-07-07 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 89
  },
  {
    "MatchNumber": 136,
    "RoundNumber": 17,
    "DateUtc": "2023-07-08 03:45:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 116,
    "AwayTeamScore": 35
  },
  {
    "MatchNumber": 139,
    "RoundNumber": 17,
    "DateUtc": "2023-07-08 06:35:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 85,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 141,
    "RoundNumber": 17,
    "DateUtc": "2023-07-08 09:25:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 58,
    "AwayTeamScore": 79
  },
  {
    "MatchNumber": 143,
    "RoundNumber": 17,
    "DateUtc": "2023-07-08 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 106,
    "AwayTeamScore": 73
  },
  {
    "MatchNumber": 138,
    "RoundNumber": 17,
    "DateUtc": "2023-07-09 03:10:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 125,
    "AwayTeamScore": 63
  },
  {
    "MatchNumber": 137,
    "RoundNumber": 17,
    "DateUtc": "2023-07-09 05:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Essendon",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 115,
    "AwayTeamScore": 97
  },
  {
    "MatchNumber": 144,
    "RoundNumber": 17,
    "DateUtc": "2023-07-09 06:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 45,
    "AwayTeamScore": 98
  },
  {
    "MatchNumber": 151,
    "RoundNumber": 18,
    "DateUtc": "2023-07-13 09:20:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 78,
    "AwayTeamScore": 76
  },
  {
    "MatchNumber": 149,
    "RoundNumber": 18,
    "DateUtc": "2023-07-14 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 105,
    "AwayTeamScore": 104
  },
  {
    "MatchNumber": 146,
    "RoundNumber": 18,
    "DateUtc": "2023-07-15 03:45:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 113,
    "AwayTeamScore": 67
  },
  {
    "MatchNumber": 148,
    "RoundNumber": 18,
    "DateUtc": "2023-07-15 04:10:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 51
  },
  {
    "MatchNumber": 145,
    "RoundNumber": 18,
    "DateUtc": "2023-07-15 06:35:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Carlton",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 122,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 147,
    "RoundNumber": 18,
    "DateUtc": "2023-07-15 09:25:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 122,
    "AwayTeamScore": 45
  },
  {
    "MatchNumber": 152,
    "RoundNumber": 18,
    "DateUtc": "2023-07-15 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 57,
    "AwayTeamScore": 71
  },
  {
    "MatchNumber": 150,
    "RoundNumber": 18,
    "DateUtc": "2023-07-16 03:10:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 40,
    "AwayTeamScore": 88
  },
  {
    "MatchNumber": 153,
    "RoundNumber": 18,
    "DateUtc": "2023-07-16 06:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 60,
    "AwayTeamScore": 98
  },
  {
    "MatchNumber": 156,
    "RoundNumber": 19,
    "DateUtc": "2023-07-21 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Essendon",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 49,
    "AwayTeamScore": 90
  },
  {
    "MatchNumber": 159,
    "RoundNumber": 19,
    "DateUtc": "2023-07-22 03:45:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 96,
    "AwayTeamScore": 95
  },
  {
    "MatchNumber": 155,
    "RoundNumber": 19,
    "DateUtc": "2023-07-22 04:10:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Carlton",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 140,
    "AwayTeamScore": 69
  },
  {
    "MatchNumber": 154,
    "RoundNumber": 19,
    "DateUtc": "2023-07-22 06:35:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 64,
    "AwayTeamScore": 53
  },
  {
    "MatchNumber": 161,
    "RoundNumber": 19,
    "DateUtc": "2023-07-22 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 83,
    "AwayTeamScore": 85
  },
  {
    "MatchNumber": 162,
    "RoundNumber": 19,
    "DateUtc": "2023-07-22 09:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 76,
    "AwayTeamScore": 105
  },
  {
    "MatchNumber": 157,
    "RoundNumber": 19,
    "DateUtc": "2023-07-23 03:10:00Z",
    "Location": "Manuka Oval",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 103,
    "AwayTeamScore": 63
  },
  {
    "MatchNumber": 158,
    "RoundNumber": 19,
    "DateUtc": "2023-07-23 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 97,
    "AwayTeamScore": 93
  },
  {
    "MatchNumber": 160,
    "RoundNumber": 19,
    "DateUtc": "2023-07-23 06:40:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 69,
    "AwayTeamScore": 61
  },
  {
    "MatchNumber": 163,
    "RoundNumber": 20,
    "DateUtc": "2023-07-28 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 76,
    "AwayTeamScore": 93
  },
  {
    "MatchNumber": 165,
    "RoundNumber": 20,
    "DateUtc": "2023-07-29 03:45:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 64,
    "AwayTeamScore": 71
  },
  {
    "MatchNumber": 169,
    "RoundNumber": 20,
    "DateUtc": "2023-07-29 03:45:00Z",
    "Location": "Mars Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 73,
    "AwayTeamScore": 78
  },
  {
    "MatchNumber": 166,
    "RoundNumber": 20,
    "DateUtc": "2023-07-29 06:35:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 96,
    "AwayTeamScore": 55
  },
  {
    "MatchNumber": 164,
    "RoundNumber": 20,
    "DateUtc": "2023-07-29 09:25:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Essendon",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 99,
    "AwayTeamScore": 101
  },
  {
    "MatchNumber": 170,
    "RoundNumber": 20,
    "DateUtc": "2023-07-29 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 112,
    "AwayTeamScore": 65
  },
  {
    "MatchNumber": 167,
    "RoundNumber": 20,
    "DateUtc": "2023-07-30 03:10:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 93,
    "AwayTeamScore": 122
  },
  {
    "MatchNumber": 168,
    "RoundNumber": 20,
    "DateUtc": "2023-07-30 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 98,
    "AwayTeamScore": 130
  },
  {
    "MatchNumber": 171,
    "RoundNumber": 20,
    "DateUtc": "2023-07-30 06:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 72,
    "AwayTeamScore": 67
  },
  {
    "MatchNumber": 178,
    "RoundNumber": 21,
    "DateUtc": "2023-08-04 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 126,
    "AwayTeamScore": 71
  },
  {
    "MatchNumber": 172,
    "RoundNumber": 21,
    "DateUtc": "2023-08-05 03:45:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Essendon",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 73,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 179,
    "RoundNumber": 21,
    "DateUtc": "2023-08-05 04:10:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 89,
    "AwayTeamScore": 61
  },
  {
    "MatchNumber": 175,
    "RoundNumber": 21,
    "DateUtc": "2023-08-05 06:35:00Z",
    "Location": "MCG",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 105,
    "AwayTeamScore": 73
  },
  {
    "MatchNumber": 173,
    "RoundNumber": 21,
    "DateUtc": "2023-08-05 09:25:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 97,
    "AwayTeamScore": 85
  },
  {
    "MatchNumber": 174,
    "RoundNumber": 21,
    "DateUtc": "2023-08-05 09:30:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 85,
    "AwayTeamScore": 96
  },
  {
    "MatchNumber": 176,
    "RoundNumber": 21,
    "DateUtc": "2023-08-06 03:10:00Z",
    "Location": "Blundstone Arena",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 71,
    "AwayTeamScore": 103
  },
  {
    "MatchNumber": 177,
    "RoundNumber": 21,
    "DateUtc": "2023-08-06 05:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 54,
    "AwayTeamScore": 73
  },
  {
    "MatchNumber": 180,
    "RoundNumber": 21,
    "DateUtc": "2023-08-06 06:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 74,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 183,
    "RoundNumber": 22,
    "DateUtc": "2023-08-11 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 109,
    "AwayTeamScore": 101
  },
  {
    "MatchNumber": 185,
    "RoundNumber": 22,
    "DateUtc": "2023-08-12 03:45:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 86
  },
  {
    "MatchNumber": 187,
    "RoundNumber": 22,
    "DateUtc": "2023-08-12 03:45:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 114,
    "AwayTeamScore": 90
  },
  {
    "MatchNumber": 182,
    "RoundNumber": 22,
    "DateUtc": "2023-08-12 06:35:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 99,
    "AwayTeamScore": 93
  },
  {
    "MatchNumber": 181,
    "RoundNumber": 22,
    "DateUtc": "2023-08-12 09:30:00Z",
    "Location": "MCG",
    "HomeTeam": "Carlton",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 60,
    "AwayTeamScore": 56
  },
  {
    "MatchNumber": 189,
    "RoundNumber": 22,
    "DateUtc": "2023-08-12 10:10:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 33,
    "AwayTeamScore": 134
  },
  {
    "MatchNumber": 184,
    "RoundNumber": 22,
    "DateUtc": "2023-08-13 03:10:00Z",
    "Location": "University of Tasmania Stadium",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 67,
    "AwayTeamScore": 64
  },
  {
    "MatchNumber": 186,
    "RoundNumber": 22,
    "DateUtc": "2023-08-13 05:20:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 93,
    "AwayTeamScore": 57
  },
  {
    "MatchNumber": 188,
    "RoundNumber": 22,
    "DateUtc": "2023-08-13 06:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 136,
    "AwayTeamScore": 85
  },
  {
    "MatchNumber": 190,
    "RoundNumber": 23,
    "DateUtc": "2023-08-18 09:50:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 100,
    "AwayTeamScore": 124
  },
  {
    "MatchNumber": 194,
    "RoundNumber": 23,
    "DateUtc": "2023-08-19 03:45:00Z",
    "Location": "MCG",
    "HomeTeam": "Richmond",
    "AwayTeam": "North Melbourne",
    "Group": null,
    "HomeTeamScore": 101,
    "AwayTeamScore": 72
  },
  {
    "MatchNumber": 191,
    "RoundNumber": 23,
    "DateUtc": "2023-08-19 04:10:00Z",
    "Location": "Heritage Bank Stadium",
    "HomeTeam": "Gold Coast Suns",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 87,
    "AwayTeamScore": 91
  },
  {
    "MatchNumber": 192,
    "RoundNumber": 23,
    "DateUtc": "2023-08-19 06:35:00Z",
    "Location": "GIANTS Stadium",
    "HomeTeam": "GWS Giants",
    "AwayTeam": "Essendon",
    "Group": null,
    "HomeTeamScore": 162,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 195,
    "RoundNumber": 23,
    "DateUtc": "2023-08-19 09:25:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "St Kilda",
    "AwayTeam": "Geelong Cats",
    "Group": null,
    "HomeTeamScore": 88,
    "AwayTeamScore": 55
  },
  {
    "MatchNumber": 197,
    "RoundNumber": 23,
    "DateUtc": "2023-08-19 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Adelaide Crows",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 73,
    "AwayTeamScore": 74
  },
  {
    "MatchNumber": 196,
    "RoundNumber": 23,
    "DateUtc": "2023-08-20 03:10:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Western Bulldogs",
    "AwayTeam": "West Coast Eagles",
    "Group": null,
    "HomeTeamScore": 85,
    "AwayTeamScore": 92
  },
  {
    "MatchNumber": 193,
    "RoundNumber": 23,
    "DateUtc": "2023-08-20 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Hawthorn",
    "Group": null,
    "HomeTeamScore": 87,
    "AwayTeamScore": 60
  },
  {
    "MatchNumber": 198,
    "RoundNumber": 23,
    "DateUtc": "2023-08-20 06:40:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Fremantle",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 58,
    "AwayTeamScore": 74
  },
  {
    "MatchNumber": 201,
    "RoundNumber": 24,
    "DateUtc": "2023-08-25 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Essendon",
    "AwayTeam": "Collingwood",
    "Group": null,
    "HomeTeamScore": 31,
    "AwayTeamScore": 101
  },
  {
    "MatchNumber": 203,
    "RoundNumber": 24,
    "DateUtc": "2023-08-26 03:45:00Z",
    "Location": "MCG",
    "HomeTeam": "Hawthorn",
    "AwayTeam": "Fremantle",
    "Group": null,
    "HomeTeamScore": 56,
    "AwayTeamScore": 93
  },
  {
    "MatchNumber": 204,
    "RoundNumber": 24,
    "DateUtc": "2023-08-26 03:45:00Z",
    "Location": "Blundstone Arena",
    "HomeTeam": "North Melbourne",
    "AwayTeam": "Gold Coast Suns",
    "Group": null,
    "HomeTeamScore": 132,
    "AwayTeamScore": 97
  },
  {
    "MatchNumber": 199,
    "RoundNumber": 24,
    "DateUtc": "2023-08-26 06:35:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "St Kilda",
    "Group": null,
    "HomeTeamScore": 72,
    "AwayTeamScore": 60
  },
  {
    "MatchNumber": 202,
    "RoundNumber": 24,
    "DateUtc": "2023-08-26 09:25:00Z",
    "Location": "GMHBA Stadium",
    "HomeTeam": "Geelong Cats",
    "AwayTeam": "Western Bulldogs",
    "Group": null,
    "HomeTeamScore": 79,
    "AwayTeamScore": 104
  },
  {
    "MatchNumber": 207,
    "RoundNumber": 24,
    "DateUtc": "2023-08-26 10:10:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "West Coast Eagles",
    "AwayTeam": "Adelaide Crows",
    "Group": null,
    "HomeTeamScore": 78,
    "AwayTeamScore": 123
  },
  {
    "MatchNumber": 206,
    "RoundNumber": 24,
    "DateUtc": "2023-08-27 02:30:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "Richmond",
    "Group": null,
    "HomeTeamScore": 94,
    "AwayTeamScore": 63
  },
  {
    "MatchNumber": 205,
    "RoundNumber": 24,
    "DateUtc": "2023-08-27 05:20:00Z",
    "Location": "SCG",
    "HomeTeam": "Sydney Swans",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 56,
    "AwayTeamScore": 77
  },
  {
    "MatchNumber": 200,
    "RoundNumber": 24,
    "DateUtc": "2023-08-27 08:10:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Carlton",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 73,
    "AwayTeamScore": 105
  },
  {
    "MatchNumber": 208,
    "RoundNumber": 25,
    "DateUtc": "2023-09-07 09:20:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Melbourne",
    "Group": null,
    "HomeTeamScore": 60,
    "AwayTeamScore": 53
  },
  {
    "MatchNumber": 209,
    "RoundNumber": 25,
    "DateUtc": "2023-09-08 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Carlton",
    "AwayTeam": "Sydney Swans",
    "Group": null,
    "HomeTeamScore": 74,
    "AwayTeamScore": 68
  },
  {
    "MatchNumber": 210,
    "RoundNumber": 25,
    "DateUtc": "2023-09-09 05:20:00Z",
    "Location": "MCG",
    "HomeTeam": "St Kilda",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 77,
    "AwayTeamScore": 101
  },
  {
    "MatchNumber": 211,
    "RoundNumber": 25,
    "DateUtc": "2023-09-09 09:25:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Port Adelaide",
    "Group": null,
    "HomeTeamScore": 123,
    "AwayTeamScore": 75
  },
  {
    "MatchNumber": 212,
    "RoundNumber": 26,
    "DateUtc": "2023-09-15 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Melbourne",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 71,
    "AwayTeamScore": 73
  },
  {
    "MatchNumber": 213,
    "RoundNumber": 26,
    "DateUtc": "2023-09-16 09:40:00Z",
    "Location": "Adelaide Oval",
    "HomeTeam": "Port Adelaide",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 70,
    "AwayTeamScore": 93
  },
  {
    "MatchNumber": 214,
    "RoundNumber": 27,
    "DateUtc": "2023-09-22 09:50:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "GWS Giants",
    "Group": null,
    "HomeTeamScore": 58,
    "AwayTeamScore": 57
  },
  {
    "MatchNumber": 215,
    "RoundNumber": 27,
    "DateUtc": "2023-09-23 07:15:00Z",
    "Location": "Gabba",
    "HomeTeam": "Brisbane Lions",
    "AwayTeam": "Carlton",
    "Group": null,
    "HomeTeamScore": 79,
    "AwayTeamScore": 63
  },
  {
    "MatchNumber": 216,
    "RoundNumber": 28,
    "DateUtc": "2023-09-30 04:30:00Z",
    "Location": "MCG",
    "HomeTeam": "Collingwood",
    "AwayTeam": "Brisbane Lions",
    "Group": null,
    "HomeTeamScore": 90,
    "AwayTeamScore": 86
  }
];
