// TODO figure out a way to keep this mock code
// out of the produciton release to avoid code bloat
// e.g. if (!kReleaseMode) {

const mockNrl2023Partial = [
  {
    "MatchNumber": 1,
    "RoundNumber": 1,
    "DateUtc": "2023-03-02 09:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 16
  }
];

const mockNrl2023Full = [
  {
    "MatchNumber": 1,
    "RoundNumber": 1,
    "DateUtc": "2023-03-02 09:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 2,
    "RoundNumber": 1,
    "DateUtc": "2023-03-03 07:00:00Z",
    "Location": "Sky Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 3,
    "RoundNumber": 1,
    "DateUtc": "2023-03-03 09:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 13
  },
  {
    "MatchNumber": 4,
    "RoundNumber": 1,
    "DateUtc": "2023-03-04 04:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 31,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 5,
    "RoundNumber": 1,
    "DateUtc": "2023-03-04 06:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 19,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 6,
    "RoundNumber": 1,
    "DateUtc": "2023-03-04 08:35:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 27
  },
  {
    "MatchNumber": 7,
    "RoundNumber": 1,
    "DateUtc": "2023-03-05 05:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 8,
    "RoundNumber": 1,
    "DateUtc": "2023-03-05 07:15:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 9,
    "RoundNumber": 2,
    "DateUtc": "2023-03-09 09:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 10,
    "RoundNumber": 2,
    "DateUtc": "2023-03-10 07:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 11,
    "RoundNumber": 2,
    "DateUtc": "2023-03-10 09:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 12,
    "RoundNumber": 2,
    "DateUtc": "2023-03-11 04:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 13,
    "RoundNumber": 2,
    "DateUtc": "2023-03-11 06:30:00Z",
    "Location": "Kayo Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 14,
    "RoundNumber": 2,
    "DateUtc": "2023-03-11 08:35:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 15,
    "RoundNumber": 2,
    "DateUtc": "2023-03-12 05:05:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 16,
    "RoundNumber": 2,
    "DateUtc": "2023-03-12 07:15:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 17,
    "RoundNumber": 3,
    "DateUtc": "2023-03-16 09:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 18,
    "RoundNumber": 3,
    "DateUtc": "2023-03-17 07:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 19,
    "RoundNumber": 3,
    "DateUtc": "2023-03-17 09:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 20,
    "RoundNumber": 3,
    "DateUtc": "2023-03-18 04:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 38,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 21,
    "RoundNumber": 3,
    "DateUtc": "2023-03-18 06:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 22,
    "RoundNumber": 3,
    "DateUtc": "2023-03-18 08:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 40,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 23,
    "RoundNumber": 3,
    "DateUtc": "2023-03-19 05:05:00Z",
    "Location": "Belmore Sports Ground",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 24,
    "RoundNumber": 3,
    "DateUtc": "2023-03-19 07:15:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 25,
    "RoundNumber": 4,
    "DateUtc": "2023-03-23 09:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 17,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 26,
    "RoundNumber": 4,
    "DateUtc": "2023-03-24 07:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 27,
    "RoundNumber": 4,
    "DateUtc": "2023-03-24 09:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 28,
    "RoundNumber": 4,
    "DateUtc": "2023-03-25 06:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 29,
    "RoundNumber": 4,
    "DateUtc": "2023-03-25 08:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 13,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 30,
    "RoundNumber": 4,
    "DateUtc": "2023-03-26 03:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 31,
    "RoundNumber": 4,
    "DateUtc": "2023-03-26 05:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 32,
    "RoundNumber": 4,
    "DateUtc": "2023-03-26 07:15:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 8,
    "AwayTeamScore": 40
  },
  {
    "MatchNumber": 33,
    "RoundNumber": 5,
    "DateUtc": "2023-03-30 09:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 34,
    "RoundNumber": 5,
    "DateUtc": "2023-03-31 07:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 53
  },
  {
    "MatchNumber": 35,
    "RoundNumber": 5,
    "DateUtc": "2023-03-31 09:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 36,
    "RoundNumber": 5,
    "DateUtc": "2023-04-01 04:00:00Z",
    "Location": "Glen Willow Oval",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 37,
    "RoundNumber": 5,
    "DateUtc": "2023-04-01 06:30:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 38,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 38,
    "RoundNumber": 5,
    "DateUtc": "2023-04-01 08:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 46,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 39,
    "RoundNumber": 5,
    "DateUtc": "2023-04-02 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 40,
    "RoundNumber": 5,
    "DateUtc": "2023-04-02 08:15:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 15,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 41,
    "RoundNumber": 6,
    "DateUtc": "2023-04-06 09:50:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 8
  },
  {
    "MatchNumber": 42,
    "RoundNumber": 6,
    "DateUtc": "2023-04-07 06:05:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 50
  },
  {
    "MatchNumber": 43,
    "RoundNumber": 6,
    "DateUtc": "2023-04-07 10:00:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 44,
    "RoundNumber": 6,
    "DateUtc": "2023-04-08 07:30:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 45,
    "RoundNumber": 6,
    "DateUtc": "2023-04-08 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 46,
    "RoundNumber": 6,
    "DateUtc": "2023-04-09 06:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 47,
    "RoundNumber": 6,
    "DateUtc": "2023-04-09 08:15:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 48,
    "RoundNumber": 6,
    "DateUtc": "2023-04-10 06:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 49,
    "RoundNumber": 7,
    "DateUtc": "2023-04-13 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 50,
    "RoundNumber": 7,
    "DateUtc": "2023-04-14 08:00:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 51,
    "RoundNumber": 7,
    "DateUtc": "2023-04-14 10:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 8
  },
  {
    "MatchNumber": 52,
    "RoundNumber": 7,
    "DateUtc": "2023-04-15 05:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 53,
    "RoundNumber": 7,
    "DateUtc": "2023-04-15 07:30:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 15,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 54,
    "RoundNumber": 7,
    "DateUtc": "2023-04-15 09:35:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 43
  },
  {
    "MatchNumber": 55,
    "RoundNumber": 7,
    "DateUtc": "2023-04-16 04:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 56,
    "RoundNumber": 7,
    "DateUtc": "2023-04-16 06:05:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 57,
    "RoundNumber": 8,
    "DateUtc": "2023-04-20 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 58,
    "RoundNumber": 8,
    "DateUtc": "2023-04-21 10:00:00Z",
    "Location": "TIO Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 59,
    "RoundNumber": 8,
    "DateUtc": "2023-04-22 07:30:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 33
  },
  {
    "MatchNumber": 60,
    "RoundNumber": 8,
    "DateUtc": "2023-04-22 09:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 61,
    "RoundNumber": 8,
    "DateUtc": "2023-04-23 04:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 62,
    "RoundNumber": 8,
    "DateUtc": "2023-04-23 06:05:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 63,
    "RoundNumber": 8,
    "DateUtc": "2023-04-25 06:05:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 27,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 64,
    "RoundNumber": 8,
    "DateUtc": "2023-04-25 09:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 65,
    "RoundNumber": 9,
    "DateUtc": "2023-04-27 09:50:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 66,
    "RoundNumber": 9,
    "DateUtc": "2023-04-28 08:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 43,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 67,
    "RoundNumber": 9,
    "DateUtc": "2023-04-28 10:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 68,
    "RoundNumber": 9,
    "DateUtc": "2023-04-29 05:00:00Z",
    "Location": "McDonalds Park",
    "HomeTeam": "Raiders",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 31,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 69,
    "RoundNumber": 9,
    "DateUtc": "2023-04-29 07:30:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 70,
    "RoundNumber": 9,
    "DateUtc": "2023-04-29 09:35:00Z",
    "Location": "Carrington Park",
    "HomeTeam": "Panthers",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 8,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 71,
    "RoundNumber": 9,
    "DateUtc": "2023-04-30 04:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 0,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 72,
    "RoundNumber": 9,
    "DateUtc": "2023-04-30 06:05:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 73,
    "RoundNumber": 10,
    "DateUtc": "2023-05-05 08:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 74,
    "RoundNumber": 10,
    "DateUtc": "2023-05-05 10:05:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 75,
    "RoundNumber": 10,
    "DateUtc": "2023-05-06 05:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 76,
    "RoundNumber": 10,
    "DateUtc": "2023-05-06 07:30:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 77,
    "RoundNumber": 10,
    "DateUtc": "2023-05-06 09:45:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Storm",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 78,
    "RoundNumber": 10,
    "DateUtc": "2023-05-07 03:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 79,
    "RoundNumber": 10,
    "DateUtc": "2023-05-07 06:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 80,
    "RoundNumber": 10,
    "DateUtc": "2023-05-07 08:25:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 81,
    "RoundNumber": 11,
    "DateUtc": "2023-05-11 09:50:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 82,
    "RoundNumber": 11,
    "DateUtc": "2023-05-12 08:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 83,
    "RoundNumber": 11,
    "DateUtc": "2023-05-12 10:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 84,
    "RoundNumber": 11,
    "DateUtc": "2023-05-13 05:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 85,
    "RoundNumber": 11,
    "DateUtc": "2023-05-13 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 86,
    "RoundNumber": 11,
    "DateUtc": "2023-05-13 09:35:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 87,
    "RoundNumber": 11,
    "DateUtc": "2023-05-14 04:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 46,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 88,
    "RoundNumber": 11,
    "DateUtc": "2023-05-14 06:05:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 89,
    "RoundNumber": 12,
    "DateUtc": "2023-05-18 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 4,
    "AwayTeamScore": 15
  },
  {
    "MatchNumber": 90,
    "RoundNumber": 12,
    "DateUtc": "2023-05-19 08:00:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 91,
    "RoundNumber": 12,
    "DateUtc": "2023-05-19 10:00:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 92,
    "RoundNumber": 12,
    "DateUtc": "2023-05-20 05:00:00Z",
    "Location": "C.ex Coffs International Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 93,
    "RoundNumber": 12,
    "DateUtc": "2023-05-20 07:30:00Z",
    "Location": "Leichhardt Oval",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 66,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 94,
    "RoundNumber": 12,
    "DateUtc": "2023-05-20 09:35:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 95,
    "RoundNumber": 12,
    "DateUtc": "2023-05-21 04:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 96,
    "RoundNumber": 12,
    "DateUtc": "2023-05-21 06:05:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 42
  },
  {
    "MatchNumber": 97,
    "RoundNumber": 13,
    "DateUtc": "2023-05-25 09:50:00Z",
    "Location": "Kayo Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 98,
    "RoundNumber": 13,
    "DateUtc": "2023-05-26 10:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 99,
    "RoundNumber": 13,
    "DateUtc": "2023-05-27 07:30:00Z",
    "Location": "McLean Park",
    "HomeTeam": "Warriors",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 100,
    "RoundNumber": 13,
    "DateUtc": "2023-05-27 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 33
  },
  {
    "MatchNumber": 101,
    "RoundNumber": 13,
    "DateUtc": "2023-05-28 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 102,
    "RoundNumber": 14,
    "DateUtc": "2023-06-02 10:00:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 19,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 103,
    "RoundNumber": 14,
    "DateUtc": "2023-06-03 05:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 8
  },
  {
    "MatchNumber": 104,
    "RoundNumber": 14,
    "DateUtc": "2023-06-03 07:30:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 46
  },
  {
    "MatchNumber": 105,
    "RoundNumber": 14,
    "DateUtc": "2023-06-03 09:35:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 106,
    "RoundNumber": 14,
    "DateUtc": "2023-06-04 04:00:00Z",
    "Location": "Industree Group Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 25,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 107,
    "RoundNumber": 14,
    "DateUtc": "2023-06-04 06:05:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 45,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 108,
    "RoundNumber": 14,
    "DateUtc": "2023-06-04 08:15:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 109,
    "RoundNumber": 15,
    "DateUtc": "2023-06-08 09:50:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 110,
    "RoundNumber": 15,
    "DateUtc": "2023-06-09 08:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 111,
    "RoundNumber": 15,
    "DateUtc": "2023-06-09 10:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 58,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 112,
    "RoundNumber": 15,
    "DateUtc": "2023-06-10 05:00:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 113,
    "RoundNumber": 15,
    "DateUtc": "2023-06-10 07:30:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 114,
    "RoundNumber": 15,
    "DateUtc": "2023-06-10 09:35:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 115,
    "RoundNumber": 15,
    "DateUtc": "2023-06-11 06:05:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 54,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 116,
    "RoundNumber": 15,
    "DateUtc": "2023-06-12 06:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 117,
    "RoundNumber": 16,
    "DateUtc": "2023-06-16 10:00:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 27,
    "AwayTeamScore": 23
  },
  {
    "MatchNumber": 118,
    "RoundNumber": 16,
    "DateUtc": "2023-06-17 05:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 119,
    "RoundNumber": 16,
    "DateUtc": "2023-06-17 07:30:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 120,
    "RoundNumber": 16,
    "DateUtc": "2023-06-17 09:35:00Z",
    "Location": "Campbelltown Sports Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 121,
    "RoundNumber": 16,
    "DateUtc": "2023-06-18 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 122,
    "RoundNumber": 17,
    "DateUtc": "2023-06-23 10:00:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 48
  },
  {
    "MatchNumber": 123,
    "RoundNumber": 17,
    "DateUtc": "2023-06-24 05:00:00Z",
    "Location": "Sunshine Coast Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 48
  },
  {
    "MatchNumber": 124,
    "RoundNumber": 17,
    "DateUtc": "2023-06-24 07:30:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 125,
    "RoundNumber": 17,
    "DateUtc": "2023-06-24 09:35:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 126,
    "RoundNumber": 17,
    "DateUtc": "2023-06-25 04:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 127,
    "RoundNumber": 17,
    "DateUtc": "2023-06-25 06:05:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 31
  },
  {
    "MatchNumber": 128,
    "RoundNumber": 17,
    "DateUtc": "2023-06-25 08:15:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 129,
    "RoundNumber": 18,
    "DateUtc": "2023-06-29 09:50:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 52,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 130,
    "RoundNumber": 18,
    "DateUtc": "2023-06-30 08:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 131,
    "RoundNumber": 18,
    "DateUtc": "2023-06-30 10:00:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Storm",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 132,
    "RoundNumber": 18,
    "DateUtc": "2023-07-01 05:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 133,
    "RoundNumber": 18,
    "DateUtc": "2023-07-01 07:30:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 74,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 134,
    "RoundNumber": 18,
    "DateUtc": "2023-07-01 09:35:00Z",
    "Location": "The Gabba",
    "HomeTeam": "Broncos",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 135,
    "RoundNumber": 18,
    "DateUtc": "2023-07-02 04:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 0,
    "AwayTeamScore": 66
  },
  {
    "MatchNumber": 136,
    "RoundNumber": 18,
    "DateUtc": "2023-07-02 06:05:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 137,
    "RoundNumber": 19,
    "DateUtc": "2023-07-06 09:50:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 138,
    "RoundNumber": 19,
    "DateUtc": "2023-07-07 10:00:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 139,
    "RoundNumber": 19,
    "DateUtc": "2023-07-08 07:30:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 46
  },
  {
    "MatchNumber": 140,
    "RoundNumber": 19,
    "DateUtc": "2023-07-08 09:35:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 141,
    "RoundNumber": 19,
    "DateUtc": "2023-07-09 06:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 21,
    "AwayTeamScore": 23
  },
  {
    "MatchNumber": 142,
    "RoundNumber": 20,
    "DateUtc": "2023-07-14 10:00:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 143,
    "RoundNumber": 20,
    "DateUtc": "2023-07-15 05:00:00Z",
    "Location": "Belmore Sports Ground",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 44
  },
  {
    "MatchNumber": 144,
    "RoundNumber": 20,
    "DateUtc": "2023-07-15 07:30:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 8,
    "AwayTeamScore": 19
  },
  {
    "MatchNumber": 145,
    "RoundNumber": 20,
    "DateUtc": "2023-07-15 09:35:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 146,
    "RoundNumber": 20,
    "DateUtc": "2023-07-16 04:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 147,
    "RoundNumber": 20,
    "DateUtc": "2023-07-16 06:05:00Z",
    "Location": "Kayo Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 148,
    "RoundNumber": 20,
    "DateUtc": "2023-07-16 08:15:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 25,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 149,
    "RoundNumber": 21,
    "DateUtc": "2023-07-20 09:50:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 150,
    "RoundNumber": 21,
    "DateUtc": "2023-07-21 08:00:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 21,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 151,
    "RoundNumber": 21,
    "DateUtc": "2023-07-21 10:00:00Z",
    "Location": "Sunshine Coast Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 20,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 152,
    "RoundNumber": 21,
    "DateUtc": "2023-07-22 05:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 36
  },
  {
    "MatchNumber": 153,
    "RoundNumber": 21,
    "DateUtc": "2023-07-22 07:30:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 154,
    "RoundNumber": 21,
    "DateUtc": "2023-07-22 09:35:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 155,
    "RoundNumber": 21,
    "DateUtc": "2023-07-23 04:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 156,
    "RoundNumber": 21,
    "DateUtc": "2023-07-23 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 157,
    "RoundNumber": 22,
    "DateUtc": "2023-07-27 09:50:00Z",
    "Location": "The Gabba",
    "HomeTeam": "Broncos",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 158,
    "RoundNumber": 22,
    "DateUtc": "2023-07-28 08:00:00Z",
    "Location": "Scully Park",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 159,
    "RoundNumber": 22,
    "DateUtc": "2023-07-28 10:00:00Z",
    "Location": "Marvel Stadium",
    "HomeTeam": "Storm",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 46,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 160,
    "RoundNumber": 22,
    "DateUtc": "2023-07-29 05:00:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 6,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 161,
    "RoundNumber": 22,
    "DateUtc": "2023-07-29 07:30:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 162,
    "RoundNumber": 22,
    "DateUtc": "2023-07-29 09:35:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 163,
    "RoundNumber": 22,
    "DateUtc": "2023-07-30 04:00:00Z",
    "Location": "Salter Oval",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 23,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 164,
    "RoundNumber": 22,
    "DateUtc": "2023-07-30 06:05:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 13
  },
  {
    "MatchNumber": 165,
    "RoundNumber": 23,
    "DateUtc": "2023-08-03 09:50:00Z",
    "Location": "Sydney Cricket Ground",
    "HomeTeam": "Roosters",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 166,
    "RoundNumber": 23,
    "DateUtc": "2023-08-04 08:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 167,
    "RoundNumber": 23,
    "DateUtc": "2023-08-04 10:00:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 168,
    "RoundNumber": 23,
    "DateUtc": "2023-08-05 05:00:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 169,
    "RoundNumber": 23,
    "DateUtc": "2023-08-05 07:30:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 170,
    "RoundNumber": 23,
    "DateUtc": "2023-08-05 09:35:00Z",
    "Location": "Optus Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 16,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 171,
    "RoundNumber": 23,
    "DateUtc": "2023-08-06 04:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 20
  },
  {
    "MatchNumber": 172,
    "RoundNumber": 23,
    "DateUtc": "2023-08-06 06:05:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 18
  },
  {
    "MatchNumber": 173,
    "RoundNumber": 24,
    "DateUtc": "2023-08-10 09:50:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 174,
    "RoundNumber": 24,
    "DateUtc": "2023-08-11 08:00:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 175,
    "RoundNumber": 24,
    "DateUtc": "2023-08-11 10:00:00Z",
    "Location": "The Gabba",
    "HomeTeam": "Broncos",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 54,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 176,
    "RoundNumber": 24,
    "DateUtc": "2023-08-12 05:00:00Z",
    "Location": "Barlow Park",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 177,
    "RoundNumber": 24,
    "DateUtc": "2023-08-12 07:30:00Z",
    "Location": "FMG Stadium Waikato",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 178,
    "RoundNumber": 24,
    "DateUtc": "2023-08-12 09:35:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 14
  },
  {
    "MatchNumber": 179,
    "RoundNumber": 24,
    "DateUtc": "2023-08-13 04:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 48,
    "AwayTeamScore": 2
  },
  {
    "MatchNumber": 180,
    "RoundNumber": 24,
    "DateUtc": "2023-08-13 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 181,
    "RoundNumber": 25,
    "DateUtc": "2023-08-17 09:50:00Z",
    "Location": "Queensland Country Bank Stadium",
    "HomeTeam": "Cowboys",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 182,
    "RoundNumber": 25,
    "DateUtc": "2023-08-18 08:00:00Z",
    "Location": "Daniel Anderson Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 29,
    "AwayTeamScore": 22
  },
  {
    "MatchNumber": 183,
    "RoundNumber": 25,
    "DateUtc": "2023-08-18 10:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Eels",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 184,
    "RoundNumber": 25,
    "DateUtc": "2023-08-19 05:00:00Z",
    "Location": "CommBank Stadium",
    "HomeTeam": "Wests Tigers",
    "AwayTeam": "Dolphins",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 23
  },
  {
    "MatchNumber": 185,
    "RoundNumber": 25,
    "DateUtc": "2023-08-19 07:30:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Panthers",
    "Group": null,
    "HomeTeamScore": 14,
    "AwayTeamScore": 40
  },
  {
    "MatchNumber": 186,
    "RoundNumber": 25,
    "DateUtc": "2023-08-19 09:35:00Z",
    "Location": "WIN Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 28,
    "AwayTeamScore": 38
  },
  {
    "MatchNumber": 187,
    "RoundNumber": 25,
    "DateUtc": "2023-08-20 04:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Rabbitohs",
    "Group": null,
    "HomeTeamScore": 29,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 188,
    "RoundNumber": 25,
    "DateUtc": "2023-08-20 06:05:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 36,
    "AwayTeamScore": 24
  },
  {
    "MatchNumber": 189,
    "RoundNumber": 26,
    "DateUtc": "2023-08-24 09:50:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Eels",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 190,
    "RoundNumber": 26,
    "DateUtc": "2023-08-25 08:00:00Z",
    "Location": "Daniel Anderson Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Dragons",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 191,
    "RoundNumber": 26,
    "DateUtc": "2023-08-25 10:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 10,
    "AwayTeamScore": 34
  },
  {
    "MatchNumber": 192,
    "RoundNumber": 26,
    "DateUtc": "2023-08-26 05:00:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Titans",
    "Group": null,
    "HomeTeamScore": 37,
    "AwayTeamScore": 16
  },
  {
    "MatchNumber": 193,
    "RoundNumber": 26,
    "DateUtc": "2023-08-26 07:30:00Z",
    "Location": "Allianz Stadium",
    "HomeTeam": "Roosters",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 8
  },
  {
    "MatchNumber": 194,
    "RoundNumber": 26,
    "DateUtc": "2023-08-26 09:35:00Z",
    "Location": "GIO Stadium",
    "HomeTeam": "Raiders",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 29
  },
  {
    "MatchNumber": 195,
    "RoundNumber": 26,
    "DateUtc": "2023-08-27 04:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Bulldogs",
    "AwayTeam": "Sea Eagles",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 42
  },
  {
    "MatchNumber": 196,
    "RoundNumber": 26,
    "DateUtc": "2023-08-27 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Sharks",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 197,
    "RoundNumber": 27,
    "DateUtc": "2023-08-31 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 22,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 198,
    "RoundNumber": 27,
    "DateUtc": "2023-09-01 08:00:00Z",
    "Location": "4 Pines Park",
    "HomeTeam": "Sea Eagles",
    "AwayTeam": "Wests Tigers",
    "Group": null,
    "HomeTeamScore": 54,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 199,
    "RoundNumber": 27,
    "DateUtc": "2023-09-01 10:00:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Rabbitohs",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 26
  },
  {
    "MatchNumber": 200,
    "RoundNumber": 27,
    "DateUtc": "2023-09-02 05:00:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Dolphins",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 201,
    "RoundNumber": 27,
    "DateUtc": "2023-09-02 07:30:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Cowboys",
    "Group": null,
    "HomeTeamScore": 44,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 202,
    "RoundNumber": 27,
    "DateUtc": "2023-09-02 09:35:00Z",
    "Location": "Netstrata Jubilee Stadium",
    "HomeTeam": "Dragons",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 32
  },
  {
    "MatchNumber": 203,
    "RoundNumber": 27,
    "DateUtc": "2023-09-03 04:00:00Z",
    "Location": "Cbus Super Stadium",
    "HomeTeam": "Titans",
    "AwayTeam": "Bulldogs",
    "Group": null,
    "HomeTeamScore": 34,
    "AwayTeamScore": 30
  },
  {
    "MatchNumber": 204,
    "RoundNumber": 27,
    "DateUtc": "2023-09-03 06:05:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 24,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 205,
    "RoundNumber": 28,
    "DateUtc": "2023-09-08 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 0
  },
  {
    "MatchNumber": 206,
    "RoundNumber": 28,
    "DateUtc": "2023-09-09 06:05:00Z",
    "Location": "BlueBet Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 32,
    "AwayTeamScore": 6
  },
  {
    "MatchNumber": 207,
    "RoundNumber": 28,
    "DateUtc": "2023-09-09 09:50:00Z",
    "Location": "PointsBet Stadium",
    "HomeTeam": "Sharks",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 12,
    "AwayTeamScore": 13
  },
  {
    "MatchNumber": 208,
    "RoundNumber": 28,
    "DateUtc": "2023-09-10 06:05:00Z",
    "Location": "McDonald Jones Stadium",
    "HomeTeam": "Knights",
    "AwayTeam": "Raiders",
    "Group": null,
    "HomeTeamScore": 30,
    "AwayTeamScore": 28
  },
  {
    "MatchNumber": 209,
    "RoundNumber": 29,
    "DateUtc": "2023-09-15 09:50:00Z",
    "Location": "AAMI Park",
    "HomeTeam": "Storm",
    "AwayTeam": "Roosters",
    "Group": null,
    "HomeTeamScore": 18,
    "AwayTeamScore": 13
  },
  {
    "MatchNumber": 210,
    "RoundNumber": 29,
    "DateUtc": "2023-09-16 06:05:00Z",
    "Location": "Mt Smart Stadium",
    "HomeTeam": "Warriors",
    "AwayTeam": "Knights",
    "Group": null,
    "HomeTeamScore": 40,
    "AwayTeamScore": 10
  },
  {
    "MatchNumber": 211,
    "RoundNumber": 30,
    "DateUtc": "2023-09-22 09:50:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Storm",
    "Group": null,
    "HomeTeamScore": 38,
    "AwayTeamScore": 4
  },
  {
    "MatchNumber": 212,
    "RoundNumber": 30,
    "DateUtc": "2023-09-23 09:50:00Z",
    "Location": "Suncorp Stadium",
    "HomeTeam": "Broncos",
    "AwayTeam": "Warriors",
    "Group": null,
    "HomeTeamScore": 42,
    "AwayTeamScore": 12
  },
  {
    "MatchNumber": 213,
    "RoundNumber": 31,
    "DateUtc": "2023-10-01 08:30:00Z",
    "Location": "Accor Stadium",
    "HomeTeam": "Panthers",
    "AwayTeam": "Broncos",
    "Group": null,
    "HomeTeamScore": 26,
    "AwayTeamScore": 24
  }
];
