// Mocks generated by Mockito 5.4.6 from annotations
// in daufootytipping/test/widgets/user_home_tips_gamelistitem_historical_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:ui' as _i18;

import 'package:carousel_slider/carousel_controller.dart' as _i5;
import 'package:daufootytipping/models/daucomp.dart' as _i7;
import 'package:daufootytipping/models/dauround.dart' as _i21;
import 'package:daufootytipping/models/game.dart' as _i4;
import 'package:daufootytipping/models/league.dart' as _i19;
import 'package:daufootytipping/models/league_ladder.dart' as _i25;
import 'package:daufootytipping/models/scoring.dart' as _i20;
import 'package:daufootytipping/models/scoring_gamestats.dart' as _i10;
import 'package:daufootytipping/models/team.dart' as _i6;
import 'package:daufootytipping/models/team_game_history_item.dart' as _i26;
import 'package:daufootytipping/models/tip.dart' as _i17;
import 'package:daufootytipping/models/tipper.dart' as _i3;
import 'package:daufootytipping/models/tipperrole.dart' as _i22;
import 'package:daufootytipping/view_models/daucomps_viewmodel.dart' as _i23;
import 'package:daufootytipping/view_models/games_viewmodel.dart' as _i9;
import 'package:daufootytipping/view_models/gametip_viewmodel.dart' as _i14;
import 'package:daufootytipping/view_models/stats_viewmodel.dart' as _i24;
import 'package:daufootytipping/view_models/teams_viewmodel.dart' as _i13;
import 'package:daufootytipping/view_models/tippers_viewmodel.dart' as _i8;
import 'package:daufootytipping/view_models/tips_viewmodel.dart' as _i2;
import 'package:flutter/material.dart' as _i12;
import 'package:flutter_svg/flutter_svg.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTipsViewModel_0 extends _i1.SmartFake implements _i2.TipsViewModel {
  _FakeTipsViewModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTipper_1 extends _i1.SmartFake implements _i3.Tipper {
  _FakeTipper_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGame_2 extends _i1.SmartFake implements _i4.Game {
  _FakeGame_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarouselSliderController_3 extends _i1.SmartFake
    implements _i5.CarouselSliderController {
  _FakeCarouselSliderController_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeam_4 extends _i1.SmartFake implements _i6.Team {
  _FakeTeam_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_5 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_6 extends _i1.SmartFake implements Uri {
  _FakeUri_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDAUComp_7 extends _i1.SmartFake implements _i7.DAUComp {
  _FakeDAUComp_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTippersViewModel_8 extends _i1.SmartFake
    implements _i8.TippersViewModel {
  _FakeTippersViewModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGamesViewModel_9 extends _i1.SmartFake
    implements _i9.GamesViewModel {
  _FakeGamesViewModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGameStatsEntry_10 extends _i1.SmartFake
    implements _i10.GameStatsEntry {
  _FakeGameStatsEntry_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSvgPicture_11 extends _i1.SmartFake implements _i11.SvgPicture {
  _FakeSvgPicture_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i12.DiagnosticLevel? minLevel = _i12.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDuration_12 extends _i1.SmartFake implements Duration {
  _FakeDuration_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeamsViewModel_13 extends _i1.SmartFake
    implements _i13.TeamsViewModel {
  _FakeTeamsViewModel_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameTipViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameTipViewModel extends _i1.Mock implements _i14.GameTipViewModel {
  MockGameTipViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TipsViewModel get allTipsViewModel => (super.noSuchMethod(
        Invocation.getter(#allTipsViewModel),
        returnValue: _FakeTipsViewModel_0(
          this,
          Invocation.getter(#allTipsViewModel),
        ),
      ) as _i2.TipsViewModel);

  @override
  _i3.Tipper get currentTipper => (super.noSuchMethod(
        Invocation.getter(#currentTipper),
        returnValue: _FakeTipper_1(
          this,
          Invocation.getter(#currentTipper),
        ),
      ) as _i3.Tipper);

  @override
  _i4.Game get game => (super.noSuchMethod(
        Invocation.getter(#game),
        returnValue: _FakeGame_2(
          this,
          Invocation.getter(#game),
        ),
      ) as _i4.Game);

  @override
  int get historicalTotalTipsOnCombination => (super.noSuchMethod(
        Invocation.getter(#historicalTotalTipsOnCombination),
        returnValue: 0,
      ) as int);

  @override
  int get historicalWinsOnCombination => (super.noSuchMethod(
        Invocation.getter(#historicalWinsOnCombination),
        returnValue: 0,
      ) as int);

  @override
  int get historicalLossesOnCombination => (super.noSuchMethod(
        Invocation.getter(#historicalLossesOnCombination),
        returnValue: 0,
      ) as int);

  @override
  int get historicalDrawsOnCombination => (super.noSuchMethod(
        Invocation.getter(#historicalDrawsOnCombination),
        returnValue: 0,
      ) as int);

  @override
  String get historicalInsightsString => (super.noSuchMethod(
        Invocation.getter(#historicalInsightsString),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#historicalInsightsString),
        ),
      ) as String);

  @override
  int get currentIndex => (super.noSuchMethod(
        Invocation.getter(#currentIndex),
        returnValue: 0,
      ) as int);

  @override
  bool get savingTip => (super.noSuchMethod(
        Invocation.getter(#savingTip),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<bool> get initialLoadCompleted => (super.noSuchMethod(
        Invocation.getter(#initialLoadCompleted),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);

  @override
  _i5.CarouselSliderController get controller => (super.noSuchMethod(
        Invocation.getter(#controller),
        returnValue: _FakeCarouselSliderController_3(
          this,
          Invocation.getter(#controller),
        ),
      ) as _i5.CarouselSliderController);

  @override
  set allTipsViewModel(_i2.TipsViewModel? _allTipsViewModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #allTipsViewModel,
          _allTipsViewModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentTipper(_i3.Tipper? _currentTipper) => super.noSuchMethod(
        Invocation.setter(
          #currentTipper,
          _currentTipper,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set game(_i4.Game? _game) => super.noSuchMethod(
        Invocation.setter(
          #game,
          _game,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set historicalTotalTipsOnCombination(
          int? _historicalTotalTipsOnCombination) =>
      super.noSuchMethod(
        Invocation.setter(
          #historicalTotalTipsOnCombination,
          _historicalTotalTipsOnCombination,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set historicalWinsOnCombination(int? _historicalWinsOnCombination) =>
      super.noSuchMethod(
        Invocation.setter(
          #historicalWinsOnCombination,
          _historicalWinsOnCombination,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set historicalLossesOnCombination(int? _historicalLossesOnCombination) =>
      super.noSuchMethod(
        Invocation.setter(
          #historicalLossesOnCombination,
          _historicalLossesOnCombination,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set historicalDrawsOnCombination(int? _historicalDrawsOnCombination) =>
      super.noSuchMethod(
        Invocation.setter(
          #historicalDrawsOnCombination,
          _historicalDrawsOnCombination,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set historicalInsightsString(String? _historicalInsightsString) =>
      super.noSuchMethod(
        Invocation.setter(
          #historicalInsightsString,
          _historicalInsightsString,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentIndex(int? _currentIndex) => super.noSuchMethod(
        Invocation.setter(
          #currentIndex,
          _currentIndex,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> testHookFetchHistoricalTipStats() => (super.noSuchMethod(
        Invocation.method(
          #testHookFetchHistoricalTipStats,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i17.Tip?> gettip() => (super.noSuchMethod(
        Invocation.method(
          #gettip,
          [],
        ),
        returnValue: _i16.Future<_i17.Tip?>.value(),
      ) as _i16.Future<_i17.Tip?>);

  @override
  void addTip(_i17.Tip? tip) => super.noSuchMethod(
        Invocation.method(
          #addTip,
          [tip],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<List<_i14.HistoricalMatchupUIData>>
      getFormattedHistoricalMatchups() => (super.noSuchMethod(
            Invocation.method(
              #getFormattedHistoricalMatchups,
              [],
            ),
            returnValue: _i16.Future<List<_i14.HistoricalMatchupUIData>>.value(
                <_i14.HistoricalMatchupUIData>[]),
          ) as _i16.Future<List<_i14.HistoricalMatchupUIData>>);

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Game].
///
/// See the documentation for Mockito's code generation for more information.
class MockGame extends _i1.Mock implements _i4.Game {
  MockGame() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get dbkey => (super.noSuchMethod(
        Invocation.getter(#dbkey),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#dbkey),
        ),
      ) as String);

  @override
  _i19.League get league => (super.noSuchMethod(
        Invocation.getter(#league),
        returnValue: _i19.League.nrl,
      ) as _i19.League);

  @override
  _i6.Team get homeTeam => (super.noSuchMethod(
        Invocation.getter(#homeTeam),
        returnValue: _FakeTeam_4(
          this,
          Invocation.getter(#homeTeam),
        ),
      ) as _i6.Team);

  @override
  _i6.Team get awayTeam => (super.noSuchMethod(
        Invocation.getter(#awayTeam),
        returnValue: _FakeTeam_4(
          this,
          Invocation.getter(#awayTeam),
        ),
      ) as _i6.Team);

  @override
  String get location => (super.noSuchMethod(
        Invocation.getter(#location),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#location),
        ),
      ) as String);

  @override
  DateTime get startTimeUTC => (super.noSuchMethod(
        Invocation.getter(#startTimeUTC),
        returnValue: _FakeDateTime_5(
          this,
          Invocation.getter(#startTimeUTC),
        ),
      ) as DateTime);

  @override
  int get fixtureRoundNumber => (super.noSuchMethod(
        Invocation.getter(#fixtureRoundNumber),
        returnValue: 0,
      ) as int);

  @override
  int get fixtureMatchNumber => (super.noSuchMethod(
        Invocation.getter(#fixtureMatchNumber),
        returnValue: 0,
      ) as int);

  @override
  _i4.GameState get gameState => (super.noSuchMethod(
        Invocation.getter(#gameState),
        returnValue: _i4.GameState.notStarted,
      ) as _i4.GameState);

  @override
  set homeTeam(_i6.Team? _homeTeam) => super.noSuchMethod(
        Invocation.setter(
          #homeTeam,
          _homeTeam,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set awayTeam(_i6.Team? _awayTeam) => super.noSuchMethod(
        Invocation.setter(
          #awayTeam,
          _awayTeam,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set scoring(_i20.Scoring? _scoring) => super.noSuchMethod(
        Invocation.setter(
          #scoring,
          _scoring,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set gameStats(_i10.GameStatsEntry? _gameStats) => super.noSuchMethod(
        Invocation.setter(
          #gameStats,
          _gameStats,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i21.DAURound? getDAURound(_i7.DAUComp? daucomp) =>
      (super.noSuchMethod(Invocation.method(
        #getDAURound,
        [daucomp],
      )) as _i21.DAURound?);

  @override
  bool isGameInRound(_i21.DAURound? round) => (super.noSuchMethod(
        Invocation.method(
          #isGameInRound,
          [round],
        ),
        returnValue: false,
      ) as bool);

  @override
  double getGameResultPercentage(_i20.GameResult? gameResult) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGameResultPercentage,
          [gameResult],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int compareTo(_i4.Game? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [Tipper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTipper extends _i1.Mock implements _i3.Tipper {
  MockTipper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get authuid => (super.noSuchMethod(
        Invocation.getter(#authuid),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#authuid),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i22.TipperRole get tipperRole => (super.noSuchMethod(
        Invocation.getter(#tipperRole),
        returnValue: _i22.TipperRole.admin,
      ) as _i22.TipperRole);

  @override
  List<_i7.DAUComp> get compsPaidFor => (super.noSuchMethod(
        Invocation.getter(#compsPaidFor),
        returnValue: <_i7.DAUComp>[],
      ) as List<_i7.DAUComp>);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  set dbkey(String? _dbkey) => super.noSuchMethod(
        Invocation.setter(
          #dbkey,
          _dbkey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authuid(String? _authuid) => super.noSuchMethod(
        Invocation.setter(
          #authuid,
          _authuid,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set email(String? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set logon(String? _logon) => super.noSuchMethod(
        Invocation.setter(
          #logon,
          _logon,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set name(String? _name) => super.noSuchMethod(
        Invocation.setter(
          #name,
          _name,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set photoURL(String? _photoURL) => super.noSuchMethod(
        Invocation.setter(
          #photoURL,
          _photoURL,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set compsPaidFor(List<_i7.DAUComp>? _compsPaidFor) => super.noSuchMethod(
        Invocation.setter(
          #compsPaidFor,
          _compsPaidFor,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool paidForComp(_i7.DAUComp? checkThisComp) => (super.noSuchMethod(
        Invocation.method(
          #paidForComp,
          [checkThisComp],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int compareTo(_i3.Tipper? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [DAUComp].
///
/// See the documentation for Mockito's code generation for more information.
class MockDAUComp extends _i1.Mock implements _i7.DAUComp {
  MockDAUComp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  Uri get aflFixtureJsonURL => (super.noSuchMethod(
        Invocation.getter(#aflFixtureJsonURL),
        returnValue: _FakeUri_6(
          this,
          Invocation.getter(#aflFixtureJsonURL),
        ),
      ) as Uri);

  @override
  Uri get nrlFixtureJsonURL => (super.noSuchMethod(
        Invocation.getter(#nrlFixtureJsonURL),
        returnValue: _FakeUri_6(
          this,
          Invocation.getter(#nrlFixtureJsonURL),
        ),
      ) as Uri);

  @override
  List<_i21.DAURound> get daurounds => (super.noSuchMethod(
        Invocation.getter(#daurounds),
        returnValue: <_i21.DAURound>[],
      ) as List<_i21.DAURound>);

  @override
  set dbkey(String? _dbkey) => super.noSuchMethod(
        Invocation.setter(
          #dbkey,
          _dbkey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set daurounds(List<_i21.DAURound>? _daurounds) => super.noSuchMethod(
        Invocation.setter(
          #daurounds,
          _daurounds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastFixtureUpdateTimestampUTC(DateTime? _lastFixtureUpdateTimestampUTC) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastFixtureUpdateTimestampUTC,
          _lastFixtureUpdateTimestampUTC,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set aflRegularCompEndDateUTC(DateTime? _aflRegularCompEndDateUTC) =>
      super.noSuchMethod(
        Invocation.setter(
          #aflRegularCompEndDateUTC,
          _aflRegularCompEndDateUTC,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set nrlRegularCompEndDateUTC(DateTime? _nrlRegularCompEndDateUTC) =>
      super.noSuchMethod(
        Invocation.setter(
          #nrlRegularCompEndDateUTC,
          _nrlRegularCompEndDateUTC,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int highestRoundNumberInPast() => (super.noSuchMethod(
        Invocation.method(
          #highestRoundNumberInPast,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  double pixelHeightUpToRound(int? roundNumber) => (super.noSuchMethod(
        Invocation.method(
          #pixelHeightUpToRound,
          [roundNumber],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  int lowestRoundNumberNotEnded() => (super.noSuchMethod(
        Invocation.method(
          #lowestRoundNumberNotEnded,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int compareTo(_i7.DAUComp? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [TipsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTipsViewModel extends _i1.Mock implements _i2.TipsViewModel {
  MockTipsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DAUComp get selectedDAUComp => (super.noSuchMethod(
        Invocation.getter(#selectedDAUComp),
        returnValue: _FakeDAUComp_7(
          this,
          Invocation.getter(#selectedDAUComp),
        ),
      ) as _i7.DAUComp);

  @override
  _i8.TippersViewModel get tipperViewModel => (super.noSuchMethod(
        Invocation.getter(#tipperViewModel),
        returnValue: _FakeTippersViewModel_8(
          this,
          Invocation.getter(#tipperViewModel),
        ),
      ) as _i8.TippersViewModel);

  @override
  _i16.Future<void> get initialLoadCompleted => (super.noSuchMethod(
        Invocation.getter(#initialLoadCompleted),
        returnValue: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i9.GamesViewModel get gamesViewModel => (super.noSuchMethod(
        Invocation.getter(#gamesViewModel),
        returnValue: _FakeGamesViewModel_9(
          this,
          Invocation.getter(#gamesViewModel),
        ),
      ) as _i9.GamesViewModel);

  @override
  set tipperViewModel(_i8.TippersViewModel? _tipperViewModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #tipperViewModel,
          _tipperViewModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<_i17.Tip?> findTip(
    _i4.Game? game,
    _i3.Tipper? tipper,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTip,
          [
            game,
            tipper,
          ],
        ),
        returnValue: _i16.Future<_i17.Tip?>.value(),
      ) as _i16.Future<_i17.Tip?>);

  @override
  _i16.Future<void> deleteTip(_i17.Tip? tip) => (super.noSuchMethod(
        Invocation.method(
          #deleteTip,
          [tip],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<bool> hasSubmittedTips(_i3.Tipper? tipper) => (super.noSuchMethod(
        Invocation.method(
          #hasSubmittedTips,
          [tipper],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);

  @override
  int numberOfOutstandingTipsForRoundAndLeague(
    _i21.DAURound? round,
    _i19.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #numberOfOutstandingTipsForRoundAndLeague,
          [
            round,
            league,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int numberOfMarginTipsSubmittedForRoundAndLeague(
    _i21.DAURound? round,
    _i19.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #numberOfMarginTipsSubmittedForRoundAndLeague,
          [
            round,
            league,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i16.Future<_i10.GameStatsEntry> percentageOfTippersTipped(_i4.Game? game) =>
      (super.noSuchMethod(
        Invocation.method(
          #percentageOfTippersTipped,
          [game],
        ),
        returnValue:
            _i16.Future<_i10.GameStatsEntry>.value(_FakeGameStatsEntry_10(
          this,
          Invocation.method(
            #percentageOfTippersTipped,
            [game],
          ),
        )),
      ) as _i16.Future<_i10.GameStatsEntry>);

  @override
  List<_i17.Tip?> getTipsForTipper(_i3.Tipper? tipper) => (super.noSuchMethod(
        Invocation.method(
          #getTipsForTipper,
          [tipper],
        ),
        returnValue: <_i17.Tip?>[],
      ) as List<_i17.Tip?>);

  @override
  _i16.Future<void> updateTip(_i17.Tip? tip) => (super.noSuchMethod(
        Invocation.method(
          #updateTip,
          [tip],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<void> deleteAllTipsForTipper(_i3.Tipper? originalTipper) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllTipsForTipper,
          [originalTipper],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Team].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeam extends _i1.Mock implements _i6.Team {
  MockTeam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get dbkey => (super.noSuchMethod(
        Invocation.getter(#dbkey),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#dbkey),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i19.League get league => (super.noSuchMethod(
        Invocation.getter(#league),
        returnValue: _i19.League.nrl,
      ) as _i19.League);

  @override
  set dbkey(String? _dbkey) => super.noSuchMethod(
        Invocation.setter(
          #dbkey,
          _dbkey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set logoURI(String? _logoURI) => super.noSuchMethod(
        Invocation.setter(
          #logoURI,
          _logoURI,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String?> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, String?>{},
      ) as Map<String, String?>);

  @override
  _i11.SvgPicture getHomeTeamLogo(_i4.Game? game) => (super.noSuchMethod(
        Invocation.method(
          #getHomeTeamLogo,
          [game],
        ),
        returnValue: _FakeSvgPicture_11(
          this,
          Invocation.method(
            #getHomeTeamLogo,
            [game],
          ),
        ),
      ) as _i11.SvgPicture);

  @override
  _i11.SvgPicture getAwayTeamLogo(_i4.Game? game) => (super.noSuchMethod(
        Invocation.method(
          #getAwayTeamLogo,
          [game],
        ),
        returnValue: _FakeSvgPicture_11(
          this,
          Invocation.method(
            #getAwayTeamLogo,
            [game],
          ),
        ),
      ) as _i11.SvgPicture);

  @override
  int compareTo(_i6.Team? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [DAUCompsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDAUCompsViewModel extends _i1.Mock implements _i23.DAUCompsViewModel {
  MockDAUCompsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get fixtureUpdateTimerDuration => (super.noSuchMethod(
        Invocation.getter(#fixtureUpdateTimerDuration),
        returnValue: _FakeDuration_12(
          this,
          Invocation.getter(#fixtureUpdateTimerDuration),
        ),
      ) as Duration);

  @override
  Map<String, dynamic> get updates => (super.noSuchMethod(
        Invocation.getter(#updates),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  List<_i4.Game> get unassignedGames => (super.noSuchMethod(
        Invocation.getter(#unassignedGames),
        returnValue: <_i4.Game>[],
      ) as List<_i4.Game>);

  @override
  List<_i7.DAUComp> get daucomps => (super.noSuchMethod(
        Invocation.getter(#daucomps),
        returnValue: <_i7.DAUComp>[],
      ) as List<_i7.DAUComp>);

  @override
  bool get savingDAUComp => (super.noSuchMethod(
        Invocation.getter(#savingDAUComp),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> get initialDAUCompLoadComplete => (super.noSuchMethod(
        Invocation.getter(#initialDAUCompLoadComplete),
        returnValue: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> get otherViewModelsLoadComplete => (super.noSuchMethod(
        Invocation.getter(#otherViewModelsLoadComplete),
        returnValue: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  bool get isDownloading => (super.noSuchMethod(
        Invocation.getter(#isDownloading),
        returnValue: false,
      ) as bool);

  @override
  bool get isLegacySyncing => (super.noSuchMethod(
        Invocation.getter(#isLegacySyncing),
        returnValue: false,
      ) as bool);

  @override
  bool get adminMode => (super.noSuchMethod(
        Invocation.getter(#adminMode),
        returnValue: false,
      ) as bool);

  @override
  bool get isLinkingGames => (super.noSuchMethod(
        Invocation.getter(#isLinkingGames),
        returnValue: false,
      ) as bool);

  @override
  set gamesViewModel(_i9.GamesViewModel? _gamesViewModel) => super.noSuchMethod(
        Invocation.setter(
          #gamesViewModel,
          _gamesViewModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set statsViewModel(_i24.StatsViewModel? _statsViewModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #statsViewModel,
          _statsViewModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selectedTipperTipsViewModel(
          _i2.TipsViewModel? _selectedTipperTipsViewModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedTipperTipsViewModel,
          _selectedTipperTipsViewModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unassignedGames(List<_i4.Game>? _unassignedGames) => super.noSuchMethod(
        Invocation.setter(
          #unassignedGames,
          _unassignedGames,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void triggerDailyEvent() => super.noSuchMethod(
        Invocation.method(
          #triggerDailyEvent,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<void> changeDisplayedDAUComp(
    _i7.DAUComp? changeToDAUComp,
    bool? changingActiveComp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeDisplayedDAUComp,
          [
            changeToDAUComp,
            changingActiveComp,
          ],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> selectedTipperChanged() => (super.noSuchMethod(
        Invocation.method(
          #selectedTipperChanged,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  bool isSelectedCompActiveComp() => (super.noSuchMethod(
        Invocation.method(
          #isSelectedCompActiveComp,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<String> getNetworkFixtureData(_i7.DAUComp? daucompToUpdate) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNetworkFixtureData,
          [daucompToUpdate],
        ),
        returnValue: _i16.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getNetworkFixtureData,
            [daucompToUpdate],
          ),
        )),
      ) as _i16.Future<String>);

  @override
  _i16.Future<void> linkGamesWithRounds(List<_i21.DAURound>? allRounds) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkGamesWithRounds,
          [allRounds],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i7.DAUComp?> findComp(String? compDbKey) => (super.noSuchMethod(
        Invocation.method(
          #findComp,
          [compDbKey],
        ),
        returnValue: _i16.Future<_i7.DAUComp?>.value(),
      ) as _i16.Future<_i7.DAUComp?>);

  @override
  void updateRoundAttribute(
    String? dauCompDbKey,
    int? roundNumber,
    String? attributeName,
    dynamic attributeValue,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateRoundAttribute,
          [
            dauCompDbKey,
            roundNumber,
            attributeName,
            attributeValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCompAttribute(
    String? dauCompDbKey,
    String? attributeName,
    dynamic attributeValue,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateCompAttribute,
          [
            dauCompDbKey,
            attributeName,
            attributeValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<void> newDAUComp(_i7.DAUComp? newDAUComp) => (super.noSuchMethod(
        Invocation.method(
          #newDAUComp,
          [newDAUComp],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> saveBatchOfCompAttributes() => (super.noSuchMethod(
        Invocation.method(
          #saveBatchOfCompAttributes,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<List<_i7.DAUComp>> getDAUcomps() => (super.noSuchMethod(
        Invocation.method(
          #getDAUcomps,
          [],
        ),
        returnValue: _i16.Future<List<_i7.DAUComp>>.value(<_i7.DAUComp>[]),
      ) as _i16.Future<List<_i7.DAUComp>>);

  @override
  Map<_i19.League, List<_i4.Game>> groupGamesIntoLeagues(
          _i21.DAURound? combinedRound) =>
      (super.noSuchMethod(
        Invocation.method(
          #groupGamesIntoLeagues,
          [combinedRound],
        ),
        returnValue: <_i19.League, List<_i4.Game>>{},
      ) as Map<_i19.League, List<_i4.Game>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearLeagueLadderCache({_i19.League? league}) => super.noSuchMethod(
        Invocation.method(
          #clearLeagueLadderCache,
          [],
          {#league: league},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<_i25.LeagueLadder?> getOrCalculateLeagueLadder(
    _i19.League? league, {
    bool? forceRecalculate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCalculateLeagueLadder,
          [league],
          {#forceRecalculate: forceRecalculate},
        ),
        returnValue: _i16.Future<_i25.LeagueLadder?>.value(),
      ) as _i16.Future<_i25.LeagueLadder?>);

  @override
  _i16.Future<Map<String, dynamic>> processAndSaveDauComp({
    required String? name,
    required String? aflFixtureJsonURL,
    required String? nrlFixtureJsonURL,
    required String? nrlRegularCompEndDateString,
    required String? aflRegularCompEndDateString,
    required _i7.DAUComp? existingComp,
    required List<_i21.DAURound>? currentRounds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processAndSaveDauComp,
          [],
          {
            #name: name,
            #aflFixtureJsonURL: aflFixtureJsonURL,
            #nrlFixtureJsonURL: nrlFixtureJsonURL,
            #nrlRegularCompEndDateString: nrlRegularCompEndDateString,
            #aflRegularCompEndDateString: aflRegularCompEndDateString,
            #existingComp: existingComp,
            #currentRounds: currentRounds,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GamesViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamesViewModel extends _i1.Mock implements _i9.GamesViewModel {
  MockGamesViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DAUComp get selectedDAUComp => (super.noSuchMethod(
        Invocation.getter(#selectedDAUComp),
        returnValue: _FakeDAUComp_7(
          this,
          Invocation.getter(#selectedDAUComp),
        ),
      ) as _i7.DAUComp);

  @override
  Map<String, dynamic> get updates => (super.noSuchMethod(
        Invocation.getter(#updates),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i16.Future<void> get initialLoadComplete => (super.noSuchMethod(
        Invocation.getter(#initialLoadComplete),
        returnValue: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i13.TeamsViewModel get teamsViewModel => (super.noSuchMethod(
        Invocation.getter(#teamsViewModel),
        returnValue: _FakeTeamsViewModel_13(
          this,
          Invocation.getter(#teamsViewModel),
        ),
      ) as _i13.TeamsViewModel);

  @override
  set selectedDAUComp(_i7.DAUComp? _selectedDAUComp) => super.noSuchMethod(
        Invocation.setter(
          #selectedDAUComp,
          _selectedDAUComp,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set testGamesByCompKey(Map<String, List<_i4.Game>>? _testGamesByCompKey) =>
      super.noSuchMethod(
        Invocation.setter(
          #testGamesByCompKey,
          _testGamesByCompKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set testGames(List<_i4.Game>? games) => super.noSuchMethod(
        Invocation.setter(
          #testGames,
          games,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> updateGameAttribute(
    String? gameDbKey,
    String? attributeName,
    dynamic attributeValue,
    String? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGameAttribute,
          [
            gameDbKey,
            attributeName,
            attributeValue,
            league,
          ],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> saveBatchOfGameAttributes() => (super.noSuchMethod(
        Invocation.method(
          #saveBatchOfGameAttributes,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<List<_i4.Game>> getGames() => (super.noSuchMethod(
        Invocation.method(
          #getGames,
          [],
        ),
        returnValue: _i16.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i16.Future<List<_i4.Game>>);

  @override
  _i16.Future<_i4.Game?> findGame(String? gameDbKey) => (super.noSuchMethod(
        Invocation.method(
          #findGame,
          [gameDbKey],
        ),
        returnValue: _i16.Future<_i4.Game?>.value(),
      ) as _i16.Future<_i4.Game?>);

  @override
  _i16.Future<List<_i4.Game>> getGamesForRound(_i21.DAURound? dauRound) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGamesForRound,
          [dauRound],
        ),
        returnValue: _i16.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i16.Future<List<_i4.Game>>);

  @override
  void removeGamesOutsideRegularComp(List<_i4.Game>? gamesForRound) =>
      super.noSuchMethod(
        Invocation.method(
          #removeGamesOutsideRegularComp,
          [gamesForRound],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<List<_i26.TeamGameHistoryItem>> getTeamGameHistory(
    _i6.Team? targetTeam,
    _i19.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamGameHistory,
          [
            targetTeam,
            league,
          ],
        ),
        returnValue: _i16.Future<List<_i26.TeamGameHistoryItem>>.value(
            <_i26.TeamGameHistoryItem>[]),
      ) as _i16.Future<List<_i26.TeamGameHistoryItem>>);

  @override
  _i16.Future<List<_i4.Game>> getCompleteMatchupHistory(
    _i6.Team? teamA,
    _i6.Team? teamB,
    _i19.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompleteMatchupHistory,
          [
            teamA,
            teamB,
            league,
          ],
        ),
        returnValue: _i16.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i16.Future<List<_i4.Game>>);

  @override
  _i16.Future<List<_i4.Game>> getMatchupHistory(
    _i6.Team? teamA,
    _i6.Team? teamB,
    _i19.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatchupHistory,
          [
            teamA,
            teamB,
            league,
          ],
        ),
        returnValue: _i16.Future<List<_i4.Game>>.value(<_i4.Game>[]),
      ) as _i16.Future<List<_i4.Game>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void completeInitialLoadForTest() => super.noSuchMethod(
        Invocation.method(
          #completeInitialLoadForTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TeamsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamsViewModel extends _i1.Mock implements _i13.TeamsViewModel {
  MockTeamsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get savingTeam => (super.noSuchMethod(
        Invocation.getter(#savingTeam),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.Team> get teams => (super.noSuchMethod(
        Invocation.getter(#teams),
        returnValue: <_i6.Team>[],
      ) as List<_i6.Team>);

  @override
  Map<dynamic, dynamic> get groupedTeams => (super.noSuchMethod(
        Invocation.getter(#groupedTeams),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i16.Future<void> get initialLoadComplete => (super.noSuchMethod(
        Invocation.getter(#initialLoadComplete),
        returnValue: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> editTeam(_i6.Team? updatedTeam) => (super.noSuchMethod(
        Invocation.method(
          #editTeam,
          [updatedTeam],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> addTeam(_i6.Team? team) => (super.noSuchMethod(
        Invocation.method(
          #addTeam,
          [team],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i6.Team? findTeam(String? teamDbKey) =>
      (super.noSuchMethod(Invocation.method(
        #findTeam,
        [teamDbKey],
      )) as _i6.Team?);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
