// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfE5gqOwR6GBEvqCo5YkWqkdPL_CTRHds',
    appId: '1:1008137398618:web:a3ac958ef2d2f101d6ab63',
    messagingSenderId: '1008137398618',
    projectId: 'dau-footy-tipping-f8a42',
    authDomain: 'dau-footy-tipping-f8a42.firebaseapp.com',
    databaseURL:
        'https://dau-footy-tipping-f8a42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dau-footy-tipping-f8a42.appspot.com',
    measurementId: 'G-V81MDHE3QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyu88ewPz06H4PFrhZqENRmd1AmjbYFwU',
    appId: '1:1008137398618:android:dae59f80f55edf7bd6ab63',
    messagingSenderId: '1008137398618',
    projectId: 'dau-footy-tipping-f8a42',
    databaseURL:
        'https://dau-footy-tipping-f8a42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dau-footy-tipping-f8a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZVs0quoE0w4lc8AsJ3q86bLylnZ1pag',
    appId: '1:1008137398618:ios:30530140c0051760d6ab63',
    messagingSenderId: '1008137398618',
    projectId: 'dau-footy-tipping-f8a42',
    databaseURL:
        'https://dau-footy-tipping-f8a42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dau-footy-tipping-f8a42.appspot.com',
    androidClientId:
        '1008137398618-fnp182b8skq0qksl7u2kdfejbh6cl7aq.apps.googleusercontent.com',
    iosClientId:
        '1008137398618-6mltcn1gj9p97p82ebar74gmrgasci97.apps.googleusercontent.com',
    iosBundleId: 'coach.interview.daufootytipping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdZVs0quoE0w4lc8AsJ3q86bLylnZ1pag',
    appId: '1:1008137398618:ios:f5b2ad52ed9d93e8d6ab63',
    messagingSenderId: '1008137398618',
    projectId: 'dau-footy-tipping-f8a42',
    databaseURL:
        'https://dau-footy-tipping-f8a42-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dau-footy-tipping-f8a42.appspot.com',
    androidClientId:
        '1008137398618-fnp182b8skq0qksl7u2kdfejbh6cl7aq.apps.googleusercontent.com',
    iosClientId:
        '1008137398618-5v7nuhp6qaef6uorfoe2j4mgv6ls613q.apps.googleusercontent.com',
    iosBundleId: 'coach.interview.daufootytipping.RunnerTests',
  );
}
