// Mocks generated by Mockito 5.4.5 from annotations
// in daufootytipping/test/mocks/mock_daucomps_viewmodel.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i13;

import 'package:daufootytipping/models/daucomp.dart' as _i8;
import 'package:daufootytipping/models/dauround.dart' as _i10;
import 'package:daufootytipping/models/game.dart' as _i12;
import 'package:daufootytipping/models/league.dart' as _i11;
import 'package:daufootytipping/view_models/daucomps_viewmodel.dart' as _i3;
import 'package:daufootytipping/view_models/games_viewmodel.dart' as _i4;
import 'package:daufootytipping/view_models/stats_viewmodel.dart' as _i5;
import 'package:daufootytipping/view_models/tips_viewmodel.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:scrollable_positioned_list/scrollable_positioned_list.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeItemScrollController_1 extends _i1.SmartFake
    implements _i2.ItemScrollController {
  _FakeItemScrollController_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [DAUCompsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDAUCompsViewModel extends _i1.Mock implements _i3.DAUCompsViewModel {
  MockDAUCompsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get fixtureUpdateTimerDuration => (super.noSuchMethod(
        Invocation.getter(#fixtureUpdateTimerDuration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#fixtureUpdateTimerDuration),
        ),
      ) as Duration);

  @override
  set gamesViewModel(_i4.GamesViewModel? _gamesViewModel) => super.noSuchMethod(
        Invocation.setter(#gamesViewModel, _gamesViewModel),
        returnValueForMissingStub: null,
      );

  @override
  set statsViewModel(_i5.StatsViewModel? _statsViewModel) => super.noSuchMethod(
        Invocation.setter(#statsViewModel, _statsViewModel),
        returnValueForMissingStub: null,
      );

  @override
  set selectedTipperTipsViewModel(
    _i6.TipsViewModel? _selectedTipperTipsViewModel,
  ) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedTipperTipsViewModel,
          _selectedTipperTipsViewModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ItemScrollController get itemScrollController => (super.noSuchMethod(
        Invocation.getter(#itemScrollController),
        returnValue: _FakeItemScrollController_1(
          this,
          Invocation.getter(#itemScrollController),
        ),
      ) as _i2.ItemScrollController);

  @override
  set itemScrollController(_i2.ItemScrollController? _itemScrollController) =>
      super.noSuchMethod(
        Invocation.setter(#itemScrollController, _itemScrollController),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> get updates => (super.noSuchMethod(
        Invocation.getter(#updates),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get savingDAUComp =>
      (super.noSuchMethod(Invocation.getter(#savingDAUComp), returnValue: false)
          as bool);

  @override
  _i7.Future<void> get initialLoadComplete => (super.noSuchMethod(
        Invocation.getter(#initialLoadComplete),
        returnValue: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool get isDownloading =>
      (super.noSuchMethod(Invocation.getter(#isDownloading), returnValue: false)
          as bool);

  @override
  bool get isLegacySyncing => (super.noSuchMethod(
        Invocation.getter(#isLegacySyncing),
        returnValue: false,
      ) as bool);

  @override
  bool get adminMode =>
      (super.noSuchMethod(Invocation.getter(#adminMode), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void triggerDailyEvent() => super.noSuchMethod(
        Invocation.method(#triggerDailyEvent, []),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> changeDisplayedDAUComp(
    _i8.DAUComp? changeToDAUComp,
    bool? changingActiveComp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#changeDisplayedDAUComp, [
          changeToDAUComp,
          changingActiveComp,
        ]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> selectedTipperChanged() => (super.noSuchMethod(
        Invocation.method(#selectedTipperChanged, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isSelectedCompActiveComp() => (super.noSuchMethod(
        Invocation.method(#isSelectedCompActiveComp, []),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<String> getNetworkFixtureData(_i8.DAUComp? daucompToUpdate) =>
      (super.noSuchMethod(
        Invocation.method(#getNetworkFixtureData, [daucompToUpdate]),
        returnValue: _i7.Future<String>.value(
          _i9.dummyValue<String>(
            this,
            Invocation.method(#getNetworkFixtureData, [daucompToUpdate]),
          ),
        ),
      ) as _i7.Future<String>);

  Map<String, List<Map<dynamic, dynamic>>> groupGamesByLeagueAndRound(
    List<Map<dynamic, dynamic>>? games,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#groupGamesByLeagueAndRound, [games]),
        returnValue: <String, List<Map<dynamic, dynamic>>>{},
      ) as Map<String, List<Map<dynamic, dynamic>>>);

  Map<String, DateTime> calculateStartEndTimes(
    List<Map<dynamic, dynamic>>? rawGames,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#calculateStartEndTimes, [rawGames]),
        returnValue: <String, DateTime>{},
      ) as Map<String, DateTime>);

  List<Map<String, Object>?> sortGameGroupsByStartTimeThenMatchNumber(
    Map<String, List<Map<dynamic, dynamic>>>? groups,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#sortGameGroupsByStartTimeThenMatchNumber, [
          groups,
        ]),
        returnValue: <Map<String, Object>?>[],
      ) as List<Map<String, Object>?>);

  List<_i10.DAURound> combineGameGroupsIntoRounds(
    List<Map<String, dynamic>>? sortedGameGroups,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#combineGameGroupsIntoRounds, [sortedGameGroups]),
        returnValue: <_i10.DAURound>[],
      ) as List<_i10.DAURound>);

  @override
  _i7.Future<void> linkGamesWithRounds(
    List<_i10.DAURound> rounds,
    _i4.GamesViewModel gamesViewModel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#linkGamesWithRounds, [
          rounds,
          gamesViewModel,
        ]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.DAUComp?> findComp(String? compDbKey) => (super.noSuchMethod(
        Invocation.method(#findComp, [compDbKey]),
        returnValue: _i7.Future<_i8.DAUComp?>.value(),
      ) as _i7.Future<_i8.DAUComp?>);

  @override
  void updateCompAttribute(
    String? dauCompDbKey,
    String? attributeName,
    dynamic attributeValue,
  ) =>
      super.noSuchMethod(
        Invocation.method(#updateCompAttribute, [
          dauCompDbKey,
          attributeName,
          attributeValue,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> newDAUComp(_i8.DAUComp? newDAUComp) => (super.noSuchMethod(
        Invocation.method(#newDAUComp, [newDAUComp]),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveBatchOfCompAttributes() => (super.noSuchMethod(
        Invocation.method(#saveBatchOfCompAttributes, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.DAUComp>> getDAUcomps() => (super.noSuchMethod(
        Invocation.method(#getDAUcomps, []),
        returnValue: _i7.Future<List<_i8.DAUComp>>.value(<_i8.DAUComp>[]),
      ) as _i7.Future<List<_i8.DAUComp>>);

  @override
  Map<_i11.League, List<_i12.Game>> groupGamesIntoLeagues(
    _i10.DAURound? combinedRound,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#groupGamesIntoLeagues, [combinedRound]),
        returnValue: <_i11.League, List<_i12.Game>>{},
      ) as Map<_i11.League, List<_i12.Game>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(#dispose, []),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(#addListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(#removeListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(#notifyListeners, []),
        returnValueForMissingStub: null,
      );
}
