// Mocks generated by Mockito 5.4.6 from annotations
// in daufootytipping/test/view_models/gametip_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;
import 'dart:ui' as _i20;

import 'package:daufootytipping/models/crowdsourcedscore.dart' as _i17;
import 'package:daufootytipping/models/daucomp.dart' as _i7;
import 'package:daufootytipping/models/dauround.dart' as _i13;
import 'package:daufootytipping/models/game.dart' as _i2;
import 'package:daufootytipping/models/league.dart' as _i16;
import 'package:daufootytipping/models/scoring.dart' as _i6;
import 'package:daufootytipping/models/scoring_gamestats.dart' as _i10;
import 'package:daufootytipping/models/team.dart' as _i15;
import 'package:daufootytipping/models/team_game_history_item.dart' as _i19;
import 'package:daufootytipping/models/tip.dart' as _i14;
import 'package:daufootytipping/models/tipper.dart' as _i3;
import 'package:daufootytipping/models/tipperrole.dart' as _i12;
import 'package:daufootytipping/view_models/games_viewmodel.dart' as _i9;
import 'package:daufootytipping/view_models/tippers_viewmodel.dart' as _i8;
import 'package:daufootytipping/view_models/tips_viewmodel.dart' as _i21;
import 'package:flutter/material.dart' as _i5;
import 'package:flutter_svg/flutter_svg.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGame_1 extends _i1.SmartFake implements _i2.Game {
  _FakeGame_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTipper_2 extends _i1.SmartFake implements _i3.Tipper {
  _FakeTipper_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSvgPicture_4 extends _i1.SmartFake implements _i4.SvgPicture {
  _FakeSvgPicture_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeScoring_5 extends _i1.SmartFake implements _i6.Scoring {
  _FakeScoring_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDAUComp_6 extends _i1.SmartFake implements _i7.DAUComp {
  _FakeDAUComp_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTippersViewModel_7 extends _i1.SmartFake
    implements _i8.TippersViewModel {
  _FakeTippersViewModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGamesViewModel_8 extends _i1.SmartFake
    implements _i9.GamesViewModel {
  _FakeGamesViewModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGameStatsEntry_9 extends _i1.SmartFake
    implements _i10.GameStatsEntry {
  _FakeGameStatsEntry_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Tipper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTipper extends _i1.Mock implements _i3.Tipper {
  MockTipper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get authuid => (super.noSuchMethod(
        Invocation.getter(#authuid),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#authuid),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i12.TipperRole get tipperRole => (super.noSuchMethod(
        Invocation.getter(#tipperRole),
        returnValue: _i12.TipperRole.admin,
      ) as _i12.TipperRole);

  @override
  List<_i7.DAUComp> get compsPaidFor => (super.noSuchMethod(
        Invocation.getter(#compsPaidFor),
        returnValue: <_i7.DAUComp>[],
      ) as List<_i7.DAUComp>);

  @override
  set dbkey(String? _dbkey) => super.noSuchMethod(
        Invocation.setter(
          #dbkey,
          _dbkey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authuid(String? _authuid) => super.noSuchMethod(
        Invocation.setter(
          #authuid,
          _authuid,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set email(String? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set logon(String? _logon) => super.noSuchMethod(
        Invocation.setter(
          #logon,
          _logon,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set name(String? _name) => super.noSuchMethod(
        Invocation.setter(
          #name,
          _name,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set photoURL(String? _photoURL) => super.noSuchMethod(
        Invocation.setter(
          #photoURL,
          _photoURL,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set compsPaidFor(List<_i7.DAUComp>? _compsPaidFor) => super.noSuchMethod(
        Invocation.setter(
          #compsPaidFor,
          _compsPaidFor,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool paidForComp(_i7.DAUComp? checkThisComp) => (super.noSuchMethod(
        Invocation.method(
          #paidForComp,
          [checkThisComp],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  int compareTo(_i3.Tipper? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [DAUComp].
///
/// See the documentation for Mockito's code generation for more information.
class MockDAUComp extends _i1.Mock implements _i7.DAUComp {
  MockDAUComp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  Uri get aflFixtureJsonURL => (super.noSuchMethod(
        Invocation.getter(#aflFixtureJsonURL),
        returnValue: _FakeUri_0(
          this,
          Invocation.getter(#aflFixtureJsonURL),
        ),
      ) as Uri);

  @override
  Uri get nrlFixtureJsonURL => (super.noSuchMethod(
        Invocation.getter(#nrlFixtureJsonURL),
        returnValue: _FakeUri_0(
          this,
          Invocation.getter(#nrlFixtureJsonURL),
        ),
      ) as Uri);

  @override
  List<_i13.DAURound> get daurounds => (super.noSuchMethod(
        Invocation.getter(#daurounds),
        returnValue: <_i13.DAURound>[],
      ) as List<_i13.DAURound>);

  @override
  set dbkey(String? _dbkey) => super.noSuchMethod(
        Invocation.setter(
          #dbkey,
          _dbkey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set daurounds(List<_i13.DAURound>? _daurounds) => super.noSuchMethod(
        Invocation.setter(
          #daurounds,
          _daurounds,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastFixtureUpdateTimestampUTC(DateTime? _lastFixtureUpdateTimestampUTC) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastFixtureUpdateTimestampUTC,
          _lastFixtureUpdateTimestampUTC,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set aflRegularCompEndDateUTC(DateTime? _aflRegularCompEndDateUTC) =>
      super.noSuchMethod(
        Invocation.setter(
          #aflRegularCompEndDateUTC,
          _aflRegularCompEndDateUTC,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set nrlRegularCompEndDateUTC(DateTime? _nrlRegularCompEndDateUTC) =>
      super.noSuchMethod(
        Invocation.setter(
          #nrlRegularCompEndDateUTC,
          _nrlRegularCompEndDateUTC,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int highestRoundNumberInPast() => (super.noSuchMethod(
        Invocation.method(
          #highestRoundNumberInPast,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  double pixelHeightUpToRound(int? roundNumber) => (super.noSuchMethod(
        Invocation.method(
          #pixelHeightUpToRound,
          [roundNumber],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  int lowestRoundNumberNotEnded() => (super.noSuchMethod(
        Invocation.method(
          #lowestRoundNumberNotEnded,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int compareTo(_i7.DAUComp? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [Tip].
///
/// See the documentation for Mockito's code generation for more information.
class MockTip extends _i1.Mock implements _i14.Tip {
  MockTip() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Game get game => (super.noSuchMethod(
        Invocation.getter(#game),
        returnValue: _FakeGame_1(
          this,
          Invocation.getter(#game),
        ),
      ) as _i2.Game);

  @override
  _i3.Tipper get tipper => (super.noSuchMethod(
        Invocation.getter(#tipper),
        returnValue: _FakeTipper_2(
          this,
          Invocation.getter(#tipper),
        ),
      ) as _i3.Tipper);

  @override
  _i6.GameResult get tip => (super.noSuchMethod(
        Invocation.getter(#tip),
        returnValue: _i6.GameResult.a,
      ) as _i6.GameResult);

  @override
  DateTime get submittedTimeUTC => (super.noSuchMethod(
        Invocation.getter(#submittedTimeUTC),
        returnValue: _FakeDateTime_3(
          this,
          Invocation.getter(#submittedTimeUTC),
        ),
      ) as DateTime);

  @override
  set dbkey(String? _dbkey) => super.noSuchMethod(
        Invocation.setter(
          #dbkey,
          _dbkey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set tipper(_i3.Tipper? _tipper) => super.noSuchMethod(
        Invocation.setter(
          #tipper,
          _tipper,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDefaultTip() => (super.noSuchMethod(
        Invocation.method(
          #isDefaultTip,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getGameResultText() => (super.noSuchMethod(
        Invocation.method(
          #getGameResultText,
          [],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #getGameResultText,
            [],
          ),
        ),
      ) as String);

  @override
  int getTipScoreCalculated() => (super.noSuchMethod(
        Invocation.method(
          #getTipScoreCalculated,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getMaxScoreCalculated() => (super.noSuchMethod(
        Invocation.method(
          #getMaxScoreCalculated,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int compareTo(_i14.Tip? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [Team].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeam extends _i1.Mock implements _i15.Team {
  MockTeam() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get dbkey => (super.noSuchMethod(
        Invocation.getter(#dbkey),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#dbkey),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i16.League get league => (super.noSuchMethod(
        Invocation.getter(#league),
        returnValue: _i16.League.nrl,
      ) as _i16.League);

  @override
  set dbkey(String? _dbkey) => super.noSuchMethod(
        Invocation.setter(
          #dbkey,
          _dbkey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set logoURI(String? _logoURI) => super.noSuchMethod(
        Invocation.setter(
          #logoURI,
          _logoURI,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.SvgPicture getHomeTeamLogo(_i2.Game? game) => (super.noSuchMethod(
        Invocation.method(
          #getHomeTeamLogo,
          [game],
        ),
        returnValue: _FakeSvgPicture_4(
          this,
          Invocation.method(
            #getHomeTeamLogo,
            [game],
          ),
        ),
      ) as _i4.SvgPicture);

  @override
  _i4.SvgPicture getAwayTeamLogo(_i2.Game? game) => (super.noSuchMethod(
        Invocation.method(
          #getAwayTeamLogo,
          [game],
        ),
        returnValue: _FakeSvgPicture_4(
          this,
          Invocation.method(
            #getAwayTeamLogo,
            [game],
          ),
        ),
      ) as _i4.SvgPicture);

  @override
  int compareTo(_i15.Team? other) => (super.noSuchMethod(
        Invocation.method(
          #compareTo,
          [other],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [Scoring].
///
/// See the documentation for Mockito's code generation for more information.
class MockScoring extends _i1.Mock implements _i6.Scoring {
  MockScoring() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set homeTeamScore(int? _homeTeamScore) => super.noSuchMethod(
        Invocation.setter(
          #homeTeamScore,
          _homeTeamScore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set awayTeamScore(int? _awayTeamScore) => super.noSuchMethod(
        Invocation.setter(
          #awayTeamScore,
          _awayTeamScore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set croudSourcedScores(List<_i17.CrowdSourcedScore>? _croudSourcedScores) =>
      super.noSuchMethod(
        Invocation.setter(
          #croudSourcedScores,
          _croudSourcedScores,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Scoring copyWith({
    int? homeTeamScore,
    int? awayTeamScore,
    List<_i17.CrowdSourcedScore>? croudSourcedScores,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #homeTeamScore: homeTeamScore,
            #awayTeamScore: awayTeamScore,
            #croudSourcedScores: croudSourcedScores,
          },
        ),
        returnValue: _FakeScoring_5(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #homeTeamScore: homeTeamScore,
              #awayTeamScore: awayTeamScore,
              #croudSourcedScores: croudSourcedScores,
            },
          ),
        ),
      ) as _i6.Scoring);

  @override
  int? currentScore(_i17.ScoringTeam? team) =>
      (super.noSuchMethod(Invocation.method(
        #currentScore,
        [team],
      )) as int?);

  @override
  bool didHomeTeamWin() => (super.noSuchMethod(
        Invocation.method(
          #didHomeTeamWin,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool didAwayTeamWin() => (super.noSuchMethod(
        Invocation.method(
          #didAwayTeamWin,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.GameResult getGameResultCalculated(_i16.League? league) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGameResultCalculated,
          [league],
        ),
        returnValue: _i6.GameResult.a,
      ) as _i6.GameResult);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [GamesViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamesViewModel extends _i1.Mock implements _i9.GamesViewModel {
  MockGamesViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DAUComp get selectedDAUComp => (super.noSuchMethod(
        Invocation.getter(#selectedDAUComp),
        returnValue: _FakeDAUComp_6(
          this,
          Invocation.getter(#selectedDAUComp),
        ),
      ) as _i7.DAUComp);

  @override
  Map<String, dynamic> get updates => (super.noSuchMethod(
        Invocation.getter(#updates),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i18.Future<void> get initialLoadComplete => (super.noSuchMethod(
        Invocation.getter(#initialLoadComplete),
        returnValue: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  set selectedDAUComp(_i7.DAUComp? _selectedDAUComp) => super.noSuchMethod(
        Invocation.setter(
          #selectedDAUComp,
          _selectedDAUComp,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set testGamesByCompKey(Map<String, List<_i2.Game>>? _testGamesByCompKey) =>
      super.noSuchMethod(
        Invocation.setter(
          #testGamesByCompKey,
          _testGamesByCompKey,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set testGames(List<_i2.Game>? games) => super.noSuchMethod(
        Invocation.setter(
          #testGames,
          games,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i18.Future<void> updateGameAttribute(
    String? gameDbKey,
    String? attributeName,
    dynamic attributeValue,
    String? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGameAttribute,
          [
            gameDbKey,
            attributeName,
            attributeValue,
            league,
          ],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> saveBatchOfGameAttributes() => (super.noSuchMethod(
        Invocation.method(
          #saveBatchOfGameAttributes,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<List<_i2.Game>> getGames() => (super.noSuchMethod(
        Invocation.method(
          #getGames,
          [],
        ),
        returnValue: _i18.Future<List<_i2.Game>>.value(<_i2.Game>[]),
      ) as _i18.Future<List<_i2.Game>>);

  @override
  _i18.Future<_i2.Game?> findGame(String? gameDbKey) => (super.noSuchMethod(
        Invocation.method(
          #findGame,
          [gameDbKey],
        ),
        returnValue: _i18.Future<_i2.Game?>.value(),
      ) as _i18.Future<_i2.Game?>);

  @override
  _i18.Future<List<_i2.Game>> getGamesForRound(_i13.DAURound? dauRound) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGamesForRound,
          [dauRound],
        ),
        returnValue: _i18.Future<List<_i2.Game>>.value(<_i2.Game>[]),
      ) as _i18.Future<List<_i2.Game>>);

  @override
  void removeGamesOutsideRegularComp(List<_i2.Game>? gamesForRound) =>
      super.noSuchMethod(
        Invocation.method(
          #removeGamesOutsideRegularComp,
          [gamesForRound],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<List<_i19.TeamGameHistoryItem>> getTeamGameHistory(
    _i15.Team? targetTeam,
    _i16.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeamGameHistory,
          [
            targetTeam,
            league,
          ],
        ),
        returnValue: _i18.Future<List<_i19.TeamGameHistoryItem>>.value(
            <_i19.TeamGameHistoryItem>[]),
      ) as _i18.Future<List<_i19.TeamGameHistoryItem>>);

  @override
  _i18.Future<List<_i2.Game>> getCompleteMatchupHistory(
    _i15.Team? teamA,
    _i15.Team? teamB,
    _i16.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompleteMatchupHistory,
          [
            teamA,
            teamB,
            league,
          ],
        ),
        returnValue: _i18.Future<List<_i2.Game>>.value(<_i2.Game>[]),
      ) as _i18.Future<List<_i2.Game>>);

  @override
  _i18.Future<List<_i2.Game>> getMatchupHistory(
    _i15.Team? teamA,
    _i15.Team? teamB,
    _i16.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatchupHistory,
          [
            teamA,
            teamB,
            league,
          ],
        ),
        returnValue: _i18.Future<List<_i2.Game>>.value(<_i2.Game>[]),
      ) as _i18.Future<List<_i2.Game>>);

  @override
  void completeInitialLoadForTest() => super.noSuchMethod(
        Invocation.method(
          #completeInitialLoadForTest,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TipsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTipsViewModel extends _i1.Mock implements _i21.TipsViewModel {
  MockTipsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DAUComp get selectedDAUComp => (super.noSuchMethod(
        Invocation.getter(#selectedDAUComp),
        returnValue: _FakeDAUComp_6(
          this,
          Invocation.getter(#selectedDAUComp),
        ),
      ) as _i7.DAUComp);

  @override
  _i8.TippersViewModel get tipperViewModel => (super.noSuchMethod(
        Invocation.getter(#tipperViewModel),
        returnValue: _FakeTippersViewModel_7(
          this,
          Invocation.getter(#tipperViewModel),
        ),
      ) as _i8.TippersViewModel);

  @override
  _i18.Future<void> get initialLoadCompleted => (super.noSuchMethod(
        Invocation.getter(#initialLoadCompleted),
        returnValue: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i9.GamesViewModel get gamesViewModel => (super.noSuchMethod(
        Invocation.getter(#gamesViewModel),
        returnValue: _FakeGamesViewModel_8(
          this,
          Invocation.getter(#gamesViewModel),
        ),
      ) as _i9.GamesViewModel);

  @override
  set tipperViewModel(_i8.TippersViewModel? _tipperViewModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #tipperViewModel,
          _tipperViewModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i18.Future<_i14.Tip?> findTip(
    _i2.Game? game,
    _i3.Tipper? tipper,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findTip,
          [
            game,
            tipper,
          ],
        ),
        returnValue: _i18.Future<_i14.Tip?>.value(),
      ) as _i18.Future<_i14.Tip?>);

  @override
  _i18.Future<void> deleteTip(_i14.Tip? tip) => (super.noSuchMethod(
        Invocation.method(
          #deleteTip,
          [tip],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<bool> hasSubmittedTips(_i3.Tipper? tipper) => (super.noSuchMethod(
        Invocation.method(
          #hasSubmittedTips,
          [tipper],
        ),
        returnValue: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  int numberOfOutstandingTipsForRoundAndLeague(
    _i13.DAURound? round,
    _i16.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #numberOfOutstandingTipsForRoundAndLeague,
          [
            round,
            league,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int numberOfMarginTipsSubmittedForRoundAndLeague(
    _i13.DAURound? round,
    _i16.League? league,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #numberOfMarginTipsSubmittedForRoundAndLeague,
          [
            round,
            league,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i18.Future<_i10.GameStatsEntry> percentageOfTippersTipped(_i2.Game? game) =>
      (super.noSuchMethod(
        Invocation.method(
          #percentageOfTippersTipped,
          [game],
        ),
        returnValue:
            _i18.Future<_i10.GameStatsEntry>.value(_FakeGameStatsEntry_9(
          this,
          Invocation.method(
            #percentageOfTippersTipped,
            [game],
          ),
        )),
      ) as _i18.Future<_i10.GameStatsEntry>);

  @override
  List<_i14.Tip?> getTipsForTipper(_i3.Tipper? tipper) => (super.noSuchMethod(
        Invocation.method(
          #getTipsForTipper,
          [tipper],
        ),
        returnValue: <_i14.Tip?>[],
      ) as List<_i14.Tip?>);

  @override
  @override
  Future<void> updateTip(_i14.Tip tip) => (super.noSuchMethod(
        Invocation.method(
          #updateTip,
          [tip],
        ),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  @override
  Future<void> deleteAllTipsForTipper(_i3.Tipper originalTipper) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllTipsForTipper,
          [originalTipper],
        ),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  void addListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
